(function(z){
var ZP=function(a){if(z.C&&!(9<=z.jh)){var b=!1;try{b=a.parentNode}catch(c){}return!!b}return z.nf(a.ownerDocument.body,a)};var $P=function(a,b){var c=b.Fd();a.bc[c]=b;for(var d in z.pB)b[z.pB[d]]&&a.vk[d].push(b);b.G=a;a.Kc()&&b.enable(a)};var aQ=function(a,b,c,d){return z.nu(a,b,c,d)};var bQ=function(a){return a.Z()&&a.ka()?new z.Ft(a):null};var cQ=function(a,b,c){z.Sr.call(this,b,a||z.BE.ba(),c)};
var dQ=function(a,b,c){for(var d=(b=1==b)?a.Z():a.ka(),f=b?a.xa():a.Sa(),g=a.Zb();d!=g&&d!=c&&!(b&&0!=f||!b&&f!=z.Qu(d));)var h=d.parentNode,d=z.kb(h.childNodes,d),f=b?d:d+1,d=h;return aQ(b?d:a.Z(),b?f:a.xa(),b?a.ka():d,b?a.Sa():f)};
var eQ=function(a){z.fo(a,!1);if(z.wG){var b=a;for(a=a.parentNode;a&&"HTML"!=a.tagName;){if(z.um?"none"==a.style[z.um].toLowerCase():(z.C||z.Lg)&&"on"==a.getAttribute("unselectable")){z.fo(a,!1,!0);for(var c=0,d=a.childNodes.length;c<d;c++){var f=a.childNodes[c];f!=b&&1==f.nodeType&&z.fo(a.childNodes[c],!0)}}b=a;a=a.parentNode}}};var fQ=function(a){var b=a.target.tagName;"TEXTAREA"!=b&&"INPUT"!=b&&a.preventDefault()};
var gQ=function(a){var b=z.Md(a);a=new z.Ld;var c=null;a.next=function(){for(;;){if(null==c){var a=b.next();c=z.Md(a)}try{return c.next()}catch(f){if(f!==z.Nd)throw f;c=null}}};return a};var hQ=function(a,b){var c=dQ(a,1,b),c=dQ(c,0,b),d=c.Z(),f=c.ka(),g=c.xa(),c=c.Sa();if(d==f){for(;f!=b&&0==g&&c==z.Qu(f);)d=f.parentNode,g=z.kb(d.childNodes,f),c=g+1,f=d;d=f}return z.nu(d,g,f,c)};
var iQ=function(a,b){z.wG&&b.g(a,"mousedown",fQ,!0);z.fo(a,!0);for(var c=a.getElementsByTagName("INPUT"),d=0,f=c.length;d<f;d++){var g=c[d];g.type in jQ&&eQ(g)}z.A(a.getElementsByTagName("TEXTAREA"),eQ)};var kQ=function(a,b,c){for(var d;a!=c&&(d=a.parentNode);){for(var f=d.cloneNode(!1);a.nextSibling;)f.appendChild(a.nextSibling);b&&f.insertBefore(b,f.firstChild);b=f;a=d}return b};var lQ=function(a){return!!mQ[a.tagName]};
var nQ=function(a){var b=["//www.zhihu.com/equation","\x26","tex"];null!=a&&b.push("\x3d",(0,window.encodeURIComponent)(String(a)));if(b[1]){a=b[0];var c=a.indexOf("#");0<=c&&(b.push(a.substr(c)),b[0]=a=a.substr(0,c));c=a.indexOf("?");0>c?b[1]="?":c==a.length-1&&(b[1]=void 0)}return b.join("")};var oQ=function(a,b){var c=z.Md(a),d=new z.Ld;d.next=function(){var a=c.next();if(b.call(void 0,a,void 0,c))return a;throw z.Nd;};return d};
var pQ=function(a,b){var c=z.Md(a),d=new z.Ld,f=!0;d.next=function(){for(;;){var a=c.next();if(!f||!b.call(void 0,a,void 0,c))return f=!1,a}};return d};var qQ=function(a){return gQ(arguments)};var rQ=function(a,b){a=z.Md(a);try{for(;;)if(b.call(void 0,a.next(),void 0,a))return!0}catch(c){if(c!==z.Nd)throw c;}return!1};var sQ=function(a){this.Re=a;this.Xy=[]};var tQ=function(a){if(!a.sy){var b=z.Ku(a.Re);a.sy=b.tagName&&"IMG"==b.tagName?b.getAttribute("alt"):z.uo(a.Re)}return a.sy};
var uQ=function(a,b,c,d){var f=new sQ(a);f.Re.href=b;c&&(a.target=c);d&&(f.Xy=d);return f};var vQ=function(a,b){var c=new sQ(a),d;d=(0,z.ab)(tQ(c));d=wQ(d)?0>d.search(/:/)?"http://"+z.Xo(d):d:xQ.test(d)?"mailto:"+d:null;c.Re.href=d?d:"";b&&(a.target=b)};
var wQ=function(a){if(/\s/.test(a)||xQ.test(a))return!1;var b=!1;/^[^:\/?#.]+:/.test(a)||(a="http://"+a,b=!0);a=a.match(z.qe);if(-1!=z.kb(["mailto","aim"],a[1]))return!0;var c=a[3];if(!c||b&&-1==c.indexOf(".")||/[^\w\d\-\u0100-\uffff.%]/.test(c))return!1;b=a[5];return!b||0==b.indexOf("/")};var yQ=function(){z.hB.call(this)};var zQ=function(a){return z.iB(a).wa()};
var AQ=function(a){if(z.C||z.Lg){var b=a.Ye(),c=b.Zb(),d=zQ(a);BQ.lastIndex=0;BQ.test(c.innerHTML)&&(a=bQ(b),"P"==c.tagName?CQ(c,!0):(b=c.innerHTML.replace(BQ,'\x3cp$1 trtempbr\x3d"temp_br"\x3e'),z.Su(c,b),c=z.vb(c.getElementsByTagName("P")),z.Od(c,function(a){"temp_br"==a.getAttribute("trtempbr")&&(a.removeAttribute("trtempbr"),z.$o(z.qf(a))&&a.appendChild(z.C?d.createTextNode(" "):d.createElement("BR")),CQ(a))})),a.restore())}};
var CQ=function(a,b){if(z.C||z.Lg){var c=a.outerHTML.replace(/<(\/?)p/gi,"\x3c$1div");b&&(c=c.replace(BQ,"\x3c/div\x3e\x3cdiv$1\x3e"));z.Lg&&!/<\/div>$/i.test(c)&&(c+="\x3c/div\x3e");a.outerHTML=c}};var DQ=function(a){return 0==a.indexOf("+")?a.substring(1):a};var EQ=function(a){a=z.Vu(a);a.align&&(a.style.textAlign=a.align,a.removeAttribute("align"))};
var FQ=function(a,b,c,d,f){var g=null;d&&(g=a.G.queryCommandValue("rtl")?"rtl":a.G.queryCommandValue("ltr")?"ltr":null);b=DQ(b);var h,k;if(z.C){var l=b;k=[];d=null;var n=a.Ye();h=z.iB(a);if(l in GQ){var q=n&&n.Zb();if(q){for(var v=z.Me("BLOCKQUOTE",null,q),F,K=0;K<v.length;K++)if(n.containsNode(v[K])){F=v[K];break}if(q=F||z.vf(q,"BLOCKQUOTE"))d=h.B("DIV",{style:"height:0"}),q.appendChild(d),k.push(d),F?n=z.nu(F,0,d,0):n.containsNode(d)&&(n=aQ(n.Z(),n.xa(),d,0)),n.select()}}F=a.G;!F.Bc()&&!d&&l in
HQ&&(F=F.m(),n&&n.isCollapsed()&&!z.jf(F)&&(d=n.Ze(0).we(),n=d.duplicate(),n.moveToElementText(F),n.collapse(!1),n.isEqual(d)&&(n=h.createTextNode(" "),F.appendChild(n),d.move("character",1),d.move("character",-1),d.select(),k.push(n))),d=h.B("DIV",{style:"height:0"}),F.appendChild(d),k.push(d));h=k[0];k=k[1]}if(z.D){h=b;var O;IQ[h]&&(O=z.iB(a).B("DIV",{style:"height: 0"},"x"),a.G.m().appendChild(O));!z.E(534)&&JQ[h]&&(h=a.G.m(),O=z.iB(a).B("DIV",{style:"height: 0"},"x"),h.insertBefore(O,h.firstChild));
h=O}z.B&&(O=b,z.E("1.9")&&"formatblock"==O.toLowerCase()&&(O=a.Ye(),F=O.Z(),O.isCollapsed()&&F&&"BODY"==F.tagName&&(d=O.xa(),(F=F.childNodes[d])&&"BR"==F.tagName&&(O=O.we(),O.setStart(F,0),O.setEnd(F,0)))));z.KG&&"fontsize"==b.toLowerCase()&&KQ(a);O=zQ(a);f&&z.AG&&(O.execCommand("styleWithCSS",!1,!0),z.Lg&&LQ(a));O.execCommand(b,!1,c);f&&z.AG&&O.execCommand("styleWithCSS",!1,!1);z.D&&!z.E("526")&&"formatblock"==b.toLowerCase()&&c&&/^[<]?h\d[>]?$/i.test(c)&&MQ(a);/insert(un)?orderedlist/i.test(b)&&
(z.D&&!z.E(534)&&NQ(a),z.C&&(OQ(a),k&&z.N(k)));h&&z.N(h);g&&a.G.execCommand(g)};
var PQ=function(a,b,c,d){var f=null,g=[],h=b&&b.Zb();if(h&&"IMG"==h.tagName||!b)return null;if(b.isCollapsed())b=b.Ze(0).we(),z.tG?(f=z.iB(a).createElement("A"),b.insertNode(f)):z.sG&&(b.pasteHTML("\x3ca id\x3d'newLink'\x3e\x3c/a\x3e"),f=z.iB(a).m("newLink"),f.removeAttribute("id"));else{var k=z.Vo();FQ(a,"CreateLink",k);z.A(a.G.m().getElementsByTagName("A"),function(a){z.bp(a.href,k)&&g.push(a)});g.length&&(f=g.pop());a=function(a){return wQ(z.uo(a))};if(g.length&&z.Mn(g,a)){for(a=0;b=g[a];a++)vQ(b,
d);g=null}}return uQ(f,c,d,g)};var KQ=function(a){var b=hQ(z.KB(a.G),a.G.m());z.Od(z.Jo(b,function(a,d,f){return 1==f.ec&&b.containsNode(a)}),function(a){z.Ig(a,"font-size","");z.B&&0==a.style.length&&null!=a.getAttribute("style")&&a.removeAttribute("style")})};var MQ=function(a){z.Od(a.Ye(),function(a){"Apple-style-span"==a.className&&(a.style.fontSize="",a.style.fontWeight="")})};
var NQ=function(a){var b=!1;z.Od(a.Ye(),function(a){var d=a.tagName;if("UL"==d||"OL"==d)if(b){if(d=z.zo(a)){var f=a.ownerDocument.createRange();f.setStartAfter(d);f.setEndBefore(a);if(z.ap(f.toString())&&d.nodeName==a.nodeName){for(;d.lastChild;)a.insertBefore(d.lastChild,a.firstChild);d.parentNode.removeChild(d)}}}else b=!0})};
var OQ=function(a){for(a=(a=a.Ye())&&a.Ic();a&&"UL"!=a.tagName&&"OL"!=a.tagName;)a=a.parentNode;a&&(a=a.parentNode);if(a){var b=z.vb(a.getElementsByTagName("UL"));z.wb(b,z.vb(a.getElementsByTagName("OL")));z.A(b,function(a){var b=a.type;b&&!("UL"==a.tagName?QQ:RQ)[b]&&(a.type="")})}};var LQ=function(a){var b=[],c=z.KB(a.G).Zb();do b.push(c);while(c=c.parentNode);a=qQ(z.Md(z.KB(a.G)),z.Md(b));a=z.Jo(a,z.Uu);z.Od(a,function(a){var b=a.style.outline;a.style.outline="0px solid red";a.style.outline=b})};
var SQ=function(a){var b=null;z.Od(a,function(a,d,f){if(-1!=f.ec){a=z.Vu(a).tagName;b=b||a;if(b!=a)throw b=null,z.Nd;f.ir()}});return b};var TQ=function(a,b){var c=b.replace("+justify","").toLowerCase();"full"==c&&(c="justify");var d=a.G.bc.Bidi;if(d)return c==d.v0();var f=a.Ye();if(!f)return!1;for(var g=f.Zb(),d=z.lb(g.childNodes,function(a){return z.Mu(a)&&f.containsNode(a,!0)}),d=d.length?d:[g],g=0;g<d.length;g++){var h=z.Vu(d[g]);if(c!=UQ(h))return!1}return!0};
var UQ=function(a){var b=z.Og(a,"textAlign"),b=b.replace(/^-(moz|webkit)-/,"");VQ[b]||(b=a.align||"left");return b};var WQ=function(a,b,c,d,f){d=DQ(d);if(f){var g=zQ(a);g.execCommand("styleWithCSS",!1,!0)}a=b?c.queryCommandState(d):c.queryCommandValue(d);f&&g.execCommand("styleWithCSS",!1,!1);return a};
var XQ=function(a,b){z.xc.call(this);this.Vu=[];for(this.Ru=[];a&&"BODY"!=a.nodeName&&a!=b;){for(var c=0,d=a.previousSibling;d;)d=d.previousSibling,++c;this.Vu.unshift(c);this.Ru.unshift(a.nodeName);a=a.parentNode}};var YQ=function(a,b){for(var c,d=b,f=0;c=a.Ru[f];++f)if(d=d.childNodes[a.Vu[f]],!d||d.nodeName!=c)return null;return d};var ZQ=function(){z.hB.call(this)};
var $Q=function(a,b){for(var c=z.KB(a.G),d=c.Ic(),f=a.G.m(),g;d&&d!=f;){var h=d.nodeName,k;(k="DIV"==h)||!(k=aR[h])||(k=!b)||(k=d,k=!(z.Ou(k)&&1==k.getElementsByTagName("BR").length));if(k){if(z.Lg&&g){"DIV"==h&&g==d.lastChild&&z.Ou(g)&&(z.df(g,d),z.Fu(g).select());break}return}z.Lg&&b&&"P"==h&&"DIV"!=h&&(g=d);d=d.parentNode}if(z.C&&!z.E(9)){var l=!1,c=c.we(),d=c.duplicate();d.moveEnd("character",1);d.text.length&&(l=d.parentElement(),d=d.duplicate(),d.collapse(!1),d=d.parentElement(),l=l!=d&&d!=
c.parentElement())&&(c.move("character",-1),c.select())}a.G.rb.wa().execCommand("FormatBlock",!1,"\x3cDIV\x3e");l&&(c.move("character",1),c.select())};
var bR=function(a){if(z.tG){if((a=z.KB(a.G))&&!a.isCollapsed()){var b=!0;if(z.Lg){var c=a.Z(),d=a.xa();c==a.ka()&&c.lastChild&&"BR"==c.lastChild.tagName&&d==c.childNodes.length-1&&(b=!1)}if(b){var f=a;if(f&&!f.isCollapsed()){var g=!0,b=f.Zb(),c=new XQ(f.Z(),b),d=f.xa(),h;h=f;var k=h.Z();z.Uu(k)&&(k=k.childNodes[h.xa()]||k);var k=z.Vu(k),l=h.ka();z.Uu(l)&&(l=l.childNodes[h.Sa()]||l);l=z.Vu(l);h=k==l;if(k=!h)a:{var l=f,k=l.ka(),l=l.Sa(),n=k;if(z.Uu(n)){var q=n.childNodes[l];if(!q||1==q.nodeType&&z.Uu(q)){k=
!1;break a}}for(q=z.Vu(n);q!=n;){if(z.Nu(n)){k=!0;break a}n=n.parentNode}k=l!=z.Qu(k)}f.Yf();(f=YQ(c,b))?f=z.Gu(f,d):(f=z.Gu(b,b.childNodes.length),g=!1);f.select();h&&(h=z.Vu(f.Z()),z.Ou(h,!0)&&(g="\x26nbsp;",z.Lg&&"LI"==h.tagName&&(g="\x3cbr\x3e"),z.Su(h,g),z.Wu(h.firstChild),g=!1));k&&(f=z.Vu(f.Z()),h=z.Nu(f),f&&h&&(z.af(f,h.childNodes),z.N(h)));g&&(f=z.Gu(YQ(c,b),d),f.select())}}}a=z.bv(a,!0)}else a=z.iB(a).wa(),b=a.selection.createRange(),c=z.Vo(),b.pasteHTML('\x3cspan id\x3d"'+c+'"\x3e\x3c/span\x3e'),
a=a.getElementById(c),a.id="";return a};var cR=function(){};var dR=function(a){z.H.call(this);this.vw=a||window;this.$A=z.G(this.vw,"resize",this.Rz,!1,this);this.Mc=z.Qe(this.vw)};
var eR=function(a,b){z.H.call(this);this.ca=z.Ie(a);this.U=new z.xd(this);this.QD=new dR(this.ca.eb());this.Ld={};this.Ud=this.ca.B("DIV",{className:fR});z.P(this.Ud,!1);a.appendChild(this.Ud);z.Ig(this.Ud,"zIndex",b);this.qo=this.Ud;this.FF=this.ca.B("DIV",{className:"tr_bubble_closebox",innerHTML:"\x26nbsp;"});this.qo.appendChild(this.FF);iQ(this.Ud,this.U);this.Qg=new z.xn(this.Ud)};var gR=function(a,b){return z.Fb(a.Ld,function(a){return a.type==b})};
var hR=function(a,b,c,d){var f=null,g;for(g in a.Ld){var h=a.Ld[g].lD;if(!f||z.nf(h,f))f=a.Ld[g].lD}return z.Bs(f,b,a.Ud,c,null,iR,d,null,a.rR())};var jR=function(a,b,c,d,f,g){this.type=c;this.lD=f;this.aX=g;this.element=a.B("DIV",{className:"tr_bubble_panel",id:b},a.B("DIV",{className:"tr_bubble_panel_title"},d?d+":":""),a.B("DIV",{className:"tr_bubble_panel_content"}))};var kR=function(){z.hB.call(this);this.rc=new z.xd(this);this.sP=null};var lR=function(a,b){return new eR(a,b)};
var mR=function(a){var b=a.g0||a.G.El.document.body;a.ca=z.Ie(b);var c=nR[a.G.id];c||(c=(a.sP||lR).call(null,b,a.G.lP||0),nR[a.G.id]=c);return c};var oR=function(a){if(a.aj){var b=mR(a),c=a.aj;z.N(b.Ld[c].element);delete b.Ld[c];c=z.Ln(b.Ld);1>=c&&z.Cg(b.Ud,"tr_multi_bubble");0==c?b.GF():b.ga();a.JH()}};var pR=function(){kR.call(this)};var qR=function(a){this.PQ=a};var rR=function(a){z.Lc.call(this,"change");this.isValid=a};var sR=function(a){z.Q.call(this,a)};
var tR=function(a,b,c,d,f,g,h,k){this.hb=b;this.Xn=h||[];b=k||uR.ba();k=[];c=-c;d=-d;for(var l=0;l<h.length;l++)k.push(a.L().B("DIV",{"class":b.V()+"-item",style:"width:"+f+"px;height:"+g+"px;background-position:"+c+"px "+d+"px;"})),c-=f;this.Og=a;z.QE.call(this,k,b,a.L())};var vR=function(a,b,c){z.Lc.call(this,a,c);this.NW=b};var uR=function(){};var wR=function(a,b,c){z.Q.call(this,c);this.qk=b;this.Og=a.MW};
var xR=function(a){var b=a.qm();if(b!=a.cJ){a.cJ=b;var c=!(1024<b.length);a.dispatchEvent(new rR(c));a=a.eX;var d=z.Ie(a);d.Mq(a);b&&(c?(b=b?nQ(b):"",b=d.B("IMG",{src:b})):(b=z.w("Equation is too long"),b=d.B("DIV",{"class":"ee-warning"},b)),d.appendChild(a,b))}};var yR=function(a,b,c){z.Q.call(this,c);this.PF=a;this.qk=b};var zR=function(a,b,c,d){z.MF.call(this,b);this.$j=new yR(a,d,b);this.$j.render();this.$j.JC(c);this.$j.addEventListener("+equation",this.zB,!1,this)};
var AR=function(a){tR.call(this,a,"a",0,150,18,18,"\\leftarrow \\rightarrow \\leftrightarrow \\Leftarrow \\Rightarrow \\Leftrightarrow \\uparrow \\downarrow \\updownarrow \\Uparrow \\Downarrow \\Updownarrow".split(" "));z.SE(this,new z.He(12,1))};var BR=function(a){tR.call(this,a,"c",0,70,18,18,"\\leq \\geq \\prec \\succ \\preceq \\succeq \\ll \\gg \\equiv \\sim \\simeq \\asymp \\approx \\ne \\subset \\supset \\subseteq \\supseteq \\in \\ni \\notin".split(" "));z.SE(this,new z.He(7,3))};
var CR=function(a){tR.call(this,a,"g",0,30,18,18,"\\alpha \\beta \\gamma \\delta \\epsilon \\varepsilon \\zeta \\eta \\theta \\vartheta \\iota \\kappa \\lambda \\mu \\nu \\xi \\pi \\varpi \\rho \\varrho \\sigma \\varsigma \\tau \\upsilon \\phi \\varphi \\chi \\psi \\omega \\Gamma \\Delta \\Theta \\Lambda \\Xi \\Pi \\Sigma \\Upsilon \\Phi \\Psi \\Omega".split(" "));z.SE(this,new z.He(7,6))};
var DR=function(a){tR.call(this,a,"m",0,90,30,56,"x_{a};x^{b};x_{a}^{b};\\bar{x};\\tilde{x};\\frac{a}{b};\\sqrt{x};\\sqrt[n]{x};\\bigcap_{a}^{b};\\bigcup_{a}^{b};\\prod_{a}^{b};\\coprod_{a}^{b};\\left( x \\right);\\left[ x \\right];\\left\\{ x \\right\\};\\left| x \\right|;\\int_{a}^{b};\\oint_{a}^{b};\\sum_{a}^{b}{x};\\lim_{a \\rightarrow b}{x}".split(";"));z.SE(this,new z.He(10,2))};var ER=function(a){tR.call(this,a,"mn",0,0,46,18,["g","s","c","m","a"],FR.ba());z.SE(this,new z.He(5,1))};
var FR=function(){};var GR=function(a){tR.call(this,a,"s",0,50,18,18,"\\times \\div \\cdot \\pm \\mp \\ast \\star \\circ \\bullet \\oplus \\ominus \\oslash \\otimes \\odot \\dagger \\ddagger \\vee \\wedge \\cap \\cup \\aleph \\Re \\Im \\top \\bot \\infty \\partial \\forall \\exists \\neg \\angle \\triangle \\diamond".split(" "));z.SE(this,new z.He(7,5))};var HR=function(a){z.H.call(this);this.zQ=a;this.AK={};this.Yn=null;this.U=new z.xd(this);this.ty=new z.td(300);this.U.g(this.ty,"tick",this.yH)};
var IR=function(a){this.qk=a||"";z.RF.call(this,"+equation")};var JR=function(){z.hB.call(this)};var KR=function(){z.hB.call(this)};var LR=function(a,b){var c=z.KB(a.G);return z.vf(c.Zb(),"LI")||rQ(c,function(a){return"LI"==a.tagName})?(a.G.execCommand(b.shiftKey?"+outdent":"+indent"),b.preventDefault(),!0):!1};var MR=function(a){z.hB.call(this);this.PU=a};var NR=function(a){z.H.call(this);this.YO=a};var OR=function(){z.H.call(this);this.LU=100;this.ie=[];this.Zk=[];this.jv=[]};
var PR=function(a,b,c){if(b.length){var d=b.pop();c.push(d);a.jv.push({type:b==a.ie?"before_undo":"before_redo",eH:b==a.ie?d.BD:d.mC,state:d});1==a.jv.length&&a.qh();0!=b.length&&1!=c.length||a.dispatchEvent("state_change")}};var QR=function(a){z.hB.call(this);a=a||new OR;this.tJ&&z.nd(this.tJ);this.gg=a;this.tJ=z.G(this.gg,"state_change",this.vQ,!1,this);this.ak={};this.Io={};this.uI=null;this.oP=(0,z.t)(this.NX,this)};
var RR=function(a,b){var c=b.Ch,d,f;b.queryCommandValue("usinglorem")?(d="",f=null):(d=b.m().innerHTML,f=new SR(b),f=f.isValid()?f:null);var g=a.Io[c];if(g){if(g.rj==d)return;if(""==d||""==g.rj){var h;h=b.wv(8,"",{});if(d==h&&""==g.rj||g.rj==h&&""==d)return}g.nC=d;g.rX=f;h=a.gg;if(0==h.ie.length||!g.equals(h.ie[h.ie.length-1])){h.ie.push(g);h.ie.length>h.LU&&h.ie.shift();var k=h.Zk.length;h.Zk.length=0;h.dispatchEvent({type:"state_added",state:g});(1==h.ie.length||k)&&h.dispatchEvent("state_change")}}a.Io[c]=
new TR(c,d,f,a.oP)};var TR=function(a,b,c,d){NR.call(this,!0);this.Po=a;this.kL=d;this.rj=b;this.zM=c};
var SR=function(a){this.te=a;var b=a.rb.eb();a=(a=z.KB(a))&&a.Fg()&&a.eb()==b?a:null;if(z.tG){if(b=a,this.pu=!1,b){var c=z.Lt(b),d=z.Nt(b);if(c&&d){a=z.Mt(b);var c=new XQ(c,this.te.m()),f=z.Ot(b),d=new XQ(d,this.te.m());b.Ih()?(this.Ea=d,this.aD=f,this.Ca=c,this.My=a):(this.Ea=c,this.aD=a,this.Ca=d,this.My=f);this.pu=!0}}}else z.sG&&(b=a,this.pu=!1,b&&(a=b.Ze(0).we(),z.nf(this.te.m(),a.parentElement())&&(b=this.te.rb.wa().body.createTextRange(),b.moveToElementText(this.te.m()),d=a.duplicate(),d.collapse(!0),
d.setEndPoint("StartToStart",b),this.Ea=UR(d),a=a.duplicate(),a.setEndPoint("StartToStart",b),this.Ca=UR(a),this.pu=!0)))};var UR=function(a){var b=a.duplicate(),c=a.text,d=c.length;b.collapse(!0);b.moveEnd("character",d);for(var f,g=10;(f=b.compareEndPoints("EndToEnd",a))&&(d-=f,b.moveEnd("character",-f),--g,0!=g););a=0;for(b=c.indexOf("\n\r");-1!=b;)++a,b=c.indexOf("\n\r",b+1);return d+a};
var VR=function(a,b){z.H.call(this);this.ea=new z.xd(this);this.te=a;this.Nb=b;this.fC=[];z.Ch(this.Nb,function(a){a.tb&&this.fC.push(WR(a.xe()))},this);this.Nb.mf(!1);this.ea.g(this.te,"cvc",this.IZ).g(this.Nb,"action",this.vR)};var WR=function(a){return a};var XR=function(a,b){z.Tz.call(this,a||z.AE.ba(),b)};var YR=function(a){z.hB.call(this);this.ll=z.sm.Ln+"/upload";z.Mb(this.J={},this.defaults,a||{})};
var ZR=function(a){var b=z.iB(a),c=(0,window.$)('\x3cdiv class\x3d"editable-dropzone"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"cell"\x3e\x3cdiv\x3e拖拽至此处上传\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e');b.yA(c[0],a.G.m());return c};
var $R=function(a){var b=z.iB(a),c=b.B("IMG",{"class":"",style:"display:block",src:z.sm.cD+"/img/spinner2.gif"}),d=z.KB(a.G);d&&z.fv(d)&&z.nf(a.G.m(),d.Zb())?d.fj(c):z.Ou(a.G.Ka)?z.ef(a.G.m(),c,0):a.G.m().appendChild(c);z.C||(z.Xu(c,!1),b.eb().focus());z.MB(a.G);return(0,window.$)(c)};
var aS=function(a,b){var c=[{display:"none"},{display:"table",width:a.$D.width(),height:a.$D.height(),"background-color":"rgba(255, 255, 255, 0.5)"}];c[2]=window.$.extend({},c[1],{"background-color":"rgba(245, 245, 245, 0.5)"});a.nN.css(c[b])};
var bS=function(a,b){var c=new window.FormData;c.append("via","xhr2");c.append("upload_file",b);var d;d=window.$.ajaxSettings.xhr();d.withCredentials=!0;var f=window.$.ajax({url:a.ll,data:c,processData:!1,contentType:!1,xhr:function(){return d},type:"POST"}).done(function(a){"string"===window.$.type(a)&&(a=JSON.parse(a));if(1===a.code)z.T.message(a.msg);else{var b=new window.Image;b.src=a.msg[0];b.setAttribute("originImgSrc",b.src.replace("_m.jpg","_r.jpg"));b.setAttribute("data-rawWidth",a.msg[1]);
b.setAttribute("data-rawHeight",a.msg[2]);f.jE.after(b)}}).fail(function(){z.T.message("上传失败！\x3e_\x3c")}).always(function(){f.jE.remove()});f.jE=$R(a)};var cS=function(){z.hB.call(this)};var dS=function(a){return a&&"BR"===a.tagName};
var eS=function(a,b){function c(a,b){return{PC:a,QJ:b}}z.D&&(a.normalize(),b=z.Cu());var d=fS(b);if(!d)return c(!1,null);if(z.Ou(a))return c(!0,a);for(var f=d;f!==a;){if(z.Nu(f))return c(!1,null);f=f.parentNode}if(dS(d)&&dS(d.previousSibling))return c(!0,d);d=b.Zb();return!d||1!==d.nodeType||d.childNodes.length&&!z.Ou(d)?c(!1,null):c(!0,d)};var fS=function(a){var b=a.ka(),c=a.Sa();a=a.Ic();var d=a.childNodes.length;3!==b.nodeType&&d&&(b=a.childNodes[c===d?d-1:c]);return b};
var gS=function(a){z.Q.call(this);z.Mb(this.J={},this.defaults,a||{});this.Ie=null};var hS=function(a){var b=z.ha(a);a=b.next().value;b=b.next().value;return{label:a,value:b,toString:z.hb(a)}};var iS=function(a){var b=z.pb(jS,function(b){var d=z.ha(b);b=d.next().value;d=d.next().value;return b===a||d===a});return b&&hS(b)};
var kS=function(a,b,c){var d=a.J,f={},g=new z.bs(lS,!1),h=new z.Fs(c,f);c=new z.ss(null,null,!1);g.gj=function(a){return function(b,c,d){(0,z.ab)(b)?a.apply(this,arguments):d(b,lS)}}(g.gj);f.rd=function(b,c,f){b=b.data;b.value===a.Ie&&(z.S.add(f,d.BF),f.appendChild(z.M("i","icon "+d.BF)));f.appendChild(window.document.createTextNode(b.toString()))};f=new z.es(g,h,c);c.Y=f;c.Fl(b);return f};
var mS=function(a,b,c){var d=a.J,f=a.o(),g=kS(a,b,c);g.Gk=20;f.g(g,"suggestionsupdate",function(){g.Cg(g.kd+0)}).g(g,"update",function(a){this.GB(a.hj)}).g(g,"dismiss",function(){this.lj(!0)});b=g.M;b.className=d.tU;b.Yh=d.BW;b.ax=d.jh;a.Y=g};var nS=function(a){z.hB.call(this);z.Mb(this.J={},this.defaults,a||{});this.Uy=this.Nb=null};var oS=function(a){return"P"===a.tagName};var pS=function(a){return 3===a.nodeType};var qS=function(a){return a&&"PRE"===a.tagName};
var rS=function(a){var b,c=new z.Ox(qS,!1,null,a),d=z.M("div",{style:"display:none"});z.zx(c,new z.Gg(4,0,0,0));z.Mx(c,new z.Gg(4,0,0,0));c.fr=150;c.pp=100;c.ai(d);c.className="hc-lang-select";z.G(c,"beforeshow",function(a){b=a.target.anchor;c.setPosition(new z.vx(b,1));if(b.lang){a=f;var d=iS(b.lang);d&&a.Da(d.value);f.lj(!0)}else f.bl("选择语言")});z.G(c,"beforehide",function(c){b=null;f.Da(null);if((c=c.target)&&a.contains(c)&&qS(c))return!1});var f=new gS;f.render(d);z.G(f,"change",function(a){b&&
(b.lang=a.AW.value,c.F(!1))});return{tz:z.hb(c),t0:z.hb(f),dispose:function(){c.dispose();f.dispose()}}};
var sS=function(a){function b(a){return z.rb(f,a)}function c(){var a=window.document.createTextNode("\n");f.push(a);return a}var d=window.document.createElement("div");d.innerHTML=a;var f=[],g=z.Qo(b);a=z.vo(d,lQ);z.A(a,function(a){a.lastChild&&"BR"===a.lastChild.tagName&&a.removeChild(a.lastChild);a.firstChild||a.appendChild(window.document.createTextNode(""));a.insertBefore(c(),a.firstChild);a.appendChild(c())});a=z.vb(d.getElementsByTagName("br"));z.A(a,function(a){a!==a.parentNode.lastChild&&
z.Bo(window.document.createTextNode("\n"),a)});d=z.vo(d,pS);d=z.To(function(a){return z.lb(a,function(c,d){var f=a[d-1];return!f||!(b(f)&&b(c))})},function(a){var b=z.Oo(a,g);return-1!==b?a.slice(0,b+1):a},function(a){var b=z.qb(a,g);return-1!==b?a.slice(b):a})(d);return z.mb(d,function(a){return a.nodeValue}).join("").replace(/\xa0/g," ")};var tS=function(a,b){a.Nb&&a.Uy&&z.Ch(a.Nb,function(a){a instanceof z.DE&&a.gb(!b||z.rb(this.Uy,a.xe()))},a)};
var uS=function(a,b,c){for(a=a.G.Ka;b!==a;){if(c(b))return b;b=b.parentNode}};var vS=function(a){var b,c=z.Cu();c&&a.G.Ka.contains(c.Zb())?(b=c.Z(),a=(b=uS(a,b,qS))?"1":"2"):a="0";return{state:a,vv:c,code:b}};var wS=function(a,b){var c=window.document.createTextNode(b);a.fj(c);z.Xu(c)};var xS=function(a,b,c){a.Bo("i",function(a,f){b.fj(a);a=f();c=z.Ka(c);z.Bo(window.document.createTextNode(c),a)})};
var yS=function(a,b){for(var c=a,d=[];c&&c!==b;)d.push([c.parentNode.childNodes.length,z.kb(c.parentNode.childNodes,c)]),c=c.parentNode;return d};var zS=function(a){var b=vS(a);a=b.vv;var c=b.code;if("1"===b.state){var b=function(a,b){return b===a.length||AS&&b===a.length-1&&"\n"===a.slice(-1)},d=a.ka(),f=yS(d,c),f=!f.length||z.Mn(f,function(a){return a[0]===a[1]+1}),g=pS(d);f&&(!g||g&&b(d.nodeValue,a.Sa()))&&BS(c)}};var BS=function(a){z.Nu(a)||z.df(window.document.createElement("br"),a)};
var CS=function(a,b){a.Bo("i",function(a,d){b.fj(a);(0,window.setTimeout)(function(){var b=window.document.createTextNode("\r");a=d();z.Bo(b,a);z.Xu(b)})})};var DS=function(a,b,c){var d=a.J,f;b.Yf();var g=ES(a,b);g?(f=window.document.createElement("PRE"),g.parentNode.insertBefore(f,g)):a.Bo("PRE",function(a,c){b.insertNode(a);f=c()});!c&&z.C&&(c=" ");f.lang=d.hQ;z.of(f,c);z.Ou(f)?z.Wu(f.firstChild):z.Xu(f.lastChild);BS(f)};
var ES=function(a,b){function c(a){return a.parentNode.insertBefore(window.document.createTextNode(""),a)}var d=z.bv(b,!0),f=d.node,g,h=a.G.Ka,k=uS(a,f,z.Ro(lQ,z.Qo(oS)))||h;if(pS(f)){var l=f.parentNode;!f.nodeValue&&l!==h&&z.Ou(l)?(g=c(l),f=c(g),l.parentNode.removeChild(l)):g=z.C&&d.offset===f.length?z.df(window.document.createTextNode(""),f):f.splitText(d.offset)}else"BR"===f.tagName&&(g=f,f=c(f));return g?(d=kQ(f,g,k),f=d.firstChild,z.af(k,d.childNodes),f):null};
var FS=function(){z.hB.call(this);this.yW=null};var GS=function(a){a.push("\x3cbr\x3e")};var HS=function(a){if(!z.KB(a.G).isCollapsed()){var b=a.yW||(0,z.t)(a.aL,a);IS(a,b);z.iB(a).wa().execCommand("RemoveFormat",!1,void 0);z.EG&&IS(a,function(a){var b=z.E("528")?/&nbsp;/g:/\u00A0/g;return a.replace(b," ")})}};var JS=function(a,b){for(var c=a.G.m();b&&b!=c;){if("TABLE"==b.tagName)return b;b=b.parentNode}return null};
var IS=function(a,b){var c=z.KB(a.G);if(!(1<c.ik())){if(z.B||z.Gc){var d=hQ(c,a.G.m()),f=JS(a,d.Z()),g=JS(a,d.ka());if(f||g){if(f==g)return;var h,k=c;h=f;var c=g,d=new z.hv(k),l=k.Z(),n=k.xa(),q=k.ka(),k=k.Sa(),v=z.iB(a);if(h){var F=v.createTextNode("");z.df(F,h);l=F;n=0}c&&(F=v.createTextNode(""),z.cf(F,c),q=F,k=0);z.nu(l,n,q,k).select();h=d;f||(c=z.N(z.Gt(h,!0)),a.$C=c);g||(c=z.N(z.Gt(h,!1)),a.Ly=c);c=z.KB(a.G);d=hQ(c,a.G.m())}d.select();c=d}l=c;c=z.iB(a).B("DIV");d=l.we();z.tG?c.appendChild(d.cloneContents()):
z.sG&&(n=l.$d(),n=n.replace(/\r\n/g,"\r"),q=n.length,l=q-z.Xo(n).length,n=q-z.Wo(n).length,d.moveStart("character",l),d.moveEnd("character",-n),l=d.htmlText,"Formatted"==d.queryCommandValue("formatBlock")&&(l=z.La(d.htmlText)),c.innerHTML=l);l=b(c.innerHTML);v=z.KB(a.G);c=z.iB(a);n=z.Vo();d=z.Vo();l='\x3cspan id\x3d"'+n+'"\x3e\x3c/span\x3e'+l+'\x3cspan id\x3d"'+d+'"\x3e\x3c/span\x3e';k=z.Vo();q='\x3cspan id\x3d"'+k+'"\x3e\x3c/span\x3e';if(z.sG){F=v.Ze(0).we();F.pasteHTML(q);for(var K;(K=F.parentElement())&&
z.Ou(K)&&!z.Ru(K);){v=K.nodeName;if("TD"==v||"TR"==v||"TH"==v)break;z.N(K)}F.pasteHTML(l);(k=c.m(k))&&z.N(k)}else if(z.tG){c.wa().execCommand("insertImage",!1,k);v=new RegExp("\x3c[^\x3c]*"+k+"[^\x3e]*\x3e");K=z.KB(a.G).Zb();3==K.nodeType&&(K=K.parentNode);for(;!v.test(K.innerHTML);)K=K.parentNode;if(z.B)z.Su(K,K.innerHTML.replace(v,l));else{z.Su(K,K.innerHTML.replace(v,q));for(K=k=c.m(k);(K=k.parentNode)&&z.Ou(K)&&!z.Ru(K);){v=K.nodeName;if("TD"==v||"TR"==v||"TH"==v)break;z.df(k,K);z.N(K)}z.Su(K,
K.innerHTML.replace(new RegExp(q,"i"),l))}}K=c.m(n);c=c.m(d);z.nu(K,0,c,c.childNodes.length).select();z.N(K);z.N(c);(z.B||z.Gc)&&h&&(c=z.KB(a.G),K=a.G.m(),a.$C&&(K.insertBefore(a.$C,K.firstChild),a.$C=null),a.Ly&&(K.appendChild(a.Ly),a.Ly=null),K=null,d=z.Gt(h,!0),l=z.Gt(h,!1),d&&l&&(K=z.nu(d,0,l,0)),f=f?K:c,g=g?K:c,aQ(f.Z(),f.xa(),g.ka(),g.Sa()).select(),h.dispose())}};var KS=function(){FS.call(this)};var LS=function(a){z.MF.call(this,a);this.U=new z.xd(this)};
var MS=function(a,b,c,d,f){z.Lc.call(this,"ok");this.SZ=a;this.RZ=b;this.RM=f;this.KY=c;this.poster=d};var NS=function(a,b){b=z.lr(b);if(!b)return!1;var c=b.match(/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-z]{2,4}\b(\/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)?/gi);c||(z.P(a.Nh,!1),a.Df.innerHTML="我们无法识别你输入的视频页地址",z.P(a.Df,!0));return c};var OS=function(){z.RF.call(this,PS);this.U=new z.xd(this)};var QS=function(){};
var RS=function(a,b){var c=[];b.enableFullScreen&&c.push("toggleFullScreen");c.push("+bold","+italic","+underline",new XR,"+blockquote","+code","+insertOrderedList","+insertUnorderedList","+equation");b.canUploadMedia_&&c.push(new XR,"image",PS);b.useRemoveFormat_&&c.push(new XR,"+removeFormat");for(var d=z.Ie(a),f=[],g=0,h;h=c[g];g++){if(z.oa(h)){var k=void 0;if(h=z.$H[h]){var k=h.factory||z.xF,l=h.Ba,n=h.na,q=h.caption,v=h.Wa,F=d||z.Ie(),k=k(l,n,q,v,null,F);h.tb&&(k.tb=!0)}h=k}h&&f.push(h)}c=z.Ie(a);
c=new cQ(z.BE.ba(),z.kG,c);d=z.ch(a);c.ci(d);c.mf(!1);for(g=0;h=f[g];g++)h.dc(32,!1),h.ci(d),c.K(h,!0);c.render(a);return c};var SS=function(a,b){var c=a.m(),d=new z.eC;d.w(c);var f=z.M("div",{style:"display:none",className:"tr-spinner spinner-gray"});b.m().appendChild(f);d.on("willScrape",function(){z.P(f,!0)}).on("didScrape",function(){z.P(f,!1)});z.Ac(a,d)};z.Ax.prototype.uz=z.Z(40,function(){return this.m().innerHTML});
z.$t.prototype.Fg=z.Z(38,function(){var a=this.bt.body.createTextRange();a.moveToElementText(this.bt.body);return this.lh(new z.$t(a,this.bt),!0)});z.lu.prototype.Fg=z.Z(37,function(){return(!this.Aa||ZP(this.Aa))&&(!this.va||ZP(this.va))&&(!(z.C&&!(9<=z.jh))||z.pu(this).Fg())});z.ru.prototype.Fg=z.Z(36,function(){var a=!1;try{a=z.Mn(this.Mi(),function(a){return z.C?!!a.parentNode:z.nf(a.ownerDocument.body,a)})}catch(b){}return a});z.xu.prototype.Fg=z.Z(35,function(){return z.Mn(z.Kt(this),function(a){return a.Fg()})});
z.Ht.prototype.ir=z.Z(34,function(){var a=this.Xc?-1:1;this.ec==a&&(this.ec=-1*a,this.depth+=this.ec*(this.Xc?-1:1))});z.Rt.prototype.ir=z.Z(33,function(){z.Rt.v.ir.apply(this);if(z.nf(this.node,this.va))throw z.Nd;});z.Hp.prototype.lj=z.Z(29,function(a,b){var c=a.Jd(),d=this.V()+"-collapse-left",f=this.V()+"-collapse-right";a.Zj(c?f:d,!!(b&1));a.Zj(c?d:f,!!(b&2))});z.Rp.prototype.lj=z.Z(28,function(a){this.M.lj(this,a)});z.Ih.prototype.xt=z.Z(24,function(){z.Kh(this);return this.Cc});
z.MF.prototype.xt=z.Z(23,function(a){return this.Bf.Dc.Jf(a)});z.$c.prototype.sm=z.Z(2,function(a,b){var c=this.vc[a.toString()],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.Ql==b&&d.push(g)}return d});z.H.prototype.sm=z.Z(1,function(a,b){return this.se.sm(String(a),b)});z.y(cQ,z.Sr);cQ.prototype.ye=function(a){cQ.v.ye.call(this,a);this.Tf||z.Wr(this)};
var jQ={text:!0,file:!0,url:!0},mQ={ADDRESS:!0,ARTICLE:!0,ASIDE:!0,BLOCKQUOTE:!0,BODY:!0,CAPTION:!0,CENTER:!0,COL:!0,COLGROUP:!0,DETAILS:!0,DIR:!0,DIV:!0,DL:!0,DD:!0,DT:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,ISINDEX:!0,OL:!0,LI:!0,MAP:!0,MENU:!0,NAV:!0,OPTGROUP:!0,OPTION:!0,P:!0,PRE:!0,SECTION:!0,SUMMARY:!0,TABLE:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0,UL:!0},PS,TS,xQ=/^[\w-]+(\.[\w-]+)*\@([\w-]+\.)+(\d+|\w\w+)$/i;z.y(yQ,z.hB);yQ.prototype.Fd=function(){return"BTF"};var US={D_:"+link",l_:"+createLink",t_:"+formatBlock",x_:"+indent",K_:"+outdent",Q_:"+strikeThrough",v_:"+insertHorizontalRule",R_:"+subscript",S_:"+superscript",V_:"+underline",h_:"+bold",y_:"+italic",s_:"+fontSize",r_:"+fontName",q_:"+foreColor",b_:"+backColor",J_:"+insertOrderedList",Z_:"+insertUnorderedList",z_:"+justifyCenter",A_:"+justifyFull",C_:"+justifyRight",B_:"+justifyLeft"},VS=z.Lo(US);yQ.prototype.ff=function(a){return a in VS};
var WS=["+createLink"];z.e=yQ.prototype;z.e.SI=function(a){return z.rb(WS,a)};z.e.Ye=function(){return z.KB(this.G)};
z.e.Ef=function(a,b,c,d){var f,g,h,k,l,n=b;switch(a){case "+backColor":if(null!==n)if(z.BG){a=n;g=z.KB(this.G);var q,v;g&&g.isCollapsed()&&(q=z.iB(this).createTextNode(z.B?" ":""),h=g.Z(),v=1==h.nodeType?h:h.parentNode,""==v.innerHTML?(v.style.textIndent="-10000px",v.appendChild(q)):(v=z.iB(this).B("SPAN",{style:"text-indent:-10000px"},q),g.fj(v)),z.Fu(q).select());FQ(this,"hiliteColor",a,!1,!0);q&&(z.B&&(q.data=""),v.style.textIndent="")}else z.Lg?FQ(this,"hiliteColor",n):FQ(this,a,n);break;case "+createLink":l=
PQ(this,b,c,d);break;case "+link":a:{l=n;this.G.Rf||z.iB(this).eb().focus();g=(a=this.Ye())&&a.Zb();if((g=z.vf(g,"A"))&&z.wf(g,z.Ru))z.ff(g);else if(l=PQ(this,a,"/",l)){if(!this.G.execCommand("link",l))if(h=this.G.El.prompt(z.kH,"http://"))a=tQ(l)||h,g=l.Re,g.href=h,n=tQ(l),a!=n&&(h=z.Ku(g),h.tagName&&"IMG"==h.tagName?h.setAttribute("alt",a?a:""):(3==h.nodeType&&(h=h.parentNode),z.uo(h)!=n&&(h=g),z.bf(h),g=z.Ie(h),h.appendChild(g.createTextNode(a))),l.sy=null),a=l.Re,z.FG?(g=a.nextSibling,g&&3==g.nodeType&&
(z.Ia(g.data," ")||z.Ia(g.data," "))||(g=z.Ie(a).createTextNode(" "),z.df(g,a)),z.Gu(g,1).select()):z.Xu(a,!1);else{a=z.Fu(l.Re);a=new z.hv(a);z.ff(l.Re);for(l.Re=null;l.Xy.length;)z.ff(l.Xy.pop());a.restore().select();l=null;break a}break a}l=null}break;case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":FQ(this,a,null,!1,!0);z.B&&FQ(this,a,null,!1,!0);z.AG&&z.B||z.Od(z.KB(this.G),EQ);break;default:z.C&&"+formatBlock"==a&&n&&(n="\x3c"+n+"\x3e");if("+foreColor"==a&&
null===n)break;switch(a){case "+indent":case "+outdent":z.AG&&(z.B&&(g=!0),z.Lg&&(g="+outdent"==a?!zQ(this).queryCommandEnabled("outdent"):!0));case "+insertOrderedList":case "+insertUnorderedList":if(q=z.IG)q=zQ(this),q=WQ(this,!0,q,a,void 0);q?h="P"!=this.G.queryCommandValue("+defaultTag"):z.JG||AQ(this);z.B&&z.HG&&!this.queryCommandValue(a)&&(q=this.G.queryCommandValue("+defaultTag"),"P"==q||"DIV"==q?q=!1:(q=this.Ye(),q.isCollapsed()&&3!=q.Ic().nodeType?(f=z.iB(this).createTextNode(" "),q.insertNode(f,
!1),z.Fu(f).select(),q=!0):q=!1),k|=q);case "+formatBlock":f=!!this.G.bc.Bidi;break;case "+subscript":case "+superscript":z.GG&&!this.queryCommandValue(a)&&(q="+subscript"==a?"+superscript":"+subscript",v=DQ(q),this.queryCommandValue(q)||zQ(this).execCommand(v,!1,null),zQ(this).execCommand(v,!1,null));break;case "+underline":case "+bold":case "+italic":g=z.B&&z.AG&&this.queryCommandValue(a);break;case "+foreColor":case "+fontName":g=z.AG&&z.B}FQ(this,a,n,f,!!g);k&&zQ(this).execCommand("Delete",!1,
!0);h&&zQ(this).execCommand("FormatBlock",!1,"\x3cdiv\x3e")}z.B&&!this.G.Eh&&z.iB(this).eb().focus();return l};
z.e.queryCommandValue=function(a){var b;switch(a){case "+link":return a=(a=this.Ye())&&a.Zb(),a=z.vf(a,"A"),!!a&&!!z.wf(a,z.Ru);case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":return TQ(this,a);case "+formatBlock":return SQ(z.KB(this.G));case "+indent":case "+outdent":case "+insertHorizontalRule":return!1;case "+fontSize":case "+fontName":case "+foreColor":case "+backColor":return this.rv(zQ(this),a,z.AG&&z.B);case "+underline":case "+bold":case "+italic":b=z.AG&&
z.B;default:var c=zQ(this);return WQ(this,!0,c,a,b)}};z.e.GK=function(a){z.yG&&a.match(/^\s*<script/i)&&(a="\x26nbsp;"+a);z.zG&&(a=a.replace(/<(\/?)strong([^\w])/gi,"\x3c$1b$2"),a=a.replace(/<(\/?)em([^\w])/gi,"\x3c$1i$2"));return a};z.e.EP=function(a){a=a.getElementsByTagName("IMG");for(var b=0,c;c=a[b];b++)if(z.C){c.removeAttribute("tabIndex");c.removeAttribute("tabIndexSet");var d=c;null!==d&&"removeAttribute"in d&&d.removeAttribute(z.va);try{delete d[z.va]}catch(f){}c.cV&&(c.tabIndex=c.cV)}};
z.e.FP=function(a){if(z.D){for(var b=z.Ne(this.G.rb.Ra,"HEAD",void 0,void 0),c=[],d=b.length,f=1;f<d;++f)for(var g=b[f].getElementsByTagName("STYLE"),h=g.length,k=0;k<h;++k)c.push(g[k].outerHTML);return c.join("")+a}return a};z.e.Nt=function(a,b,c){if(!c)return!1;var d;switch(b){case "b":d="+bold";break;case "i":d="+italic";break;case "u":d="+underline";break;case "s":return!0}return d?(this.G.execCommand(d),!0):!1};
var BQ=z.C?/<br([^\/>]*)\/?>/gi:/<br([^\/>]*)\/?>(?!<\/(div|p)>)/gi,HQ={indent:1,outdent:1,insertOrderedList:1,insertUnorderedList:1,justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,ltr:1,rtl:1},GQ={insertOrderedList:1,insertUnorderedList:1},RQ={1:1,a:1,A:1,i:1,I:1},QQ={disc:1,circle:1,square:1},IQ={justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,formatBlock:1},JQ={insertOrderedList:1,insertUnorderedList:1},VQ={center:1,justify:1,right:1,left:1};
yQ.prototype.rv=function(a,b,c){return WQ(this,!1,a,b,c)};z.y(XQ,z.xc);XQ.prototype.toString=function(){for(var a=[],b,c=0;b=this.Ru[c];c++)a.push(this.Vu[c]+","+b);return a.join("\n")};XQ.prototype.D=function(){delete this.Vu;delete this.Ru};z.y(ZQ,z.hB);z.e=ZQ.prototype;z.e.tag="DIV";z.e.Fd=function(){return"EnterHandler"};z.e.enable=function(a){ZQ.v.enable.call(this,a);!z.LG||"P"!=this.tag&&"DIV"!=this.tag||z.iB(this).wa().execCommand("opera-defaultBlock",!1,this.tag)};z.e.GK=function(a){return!a||z.$o(a)?z.yG?this.oR():"":a};z.e.oR=z.hb("\x3cbr\x3e");
z.e.oS=function(a){if(z.B&&this.G.Eh)return!1;if(8==a.keyCode){var b=z.KB(this.G),c=this.G.m(),b=b&&b.Z();c.firstChild==b&&z.Ou(b)&&(a.preventDefault(),a.stopPropagation())}else if(13==a.keyCode)if(z.B){if(!a.shiftKey){var c=z.KB(this.G),b=!c||c.isCollapsed(),d=bR(this),f=this.G.execCommand("+splitBlockquote",d);f&&(a.preventDefault(),a.stopPropagation());z.tG||d.removeNode(!0);f||this.bS(a,b,c)}}else{this.G.Ii();c=bR(this);if(b=!!this.G.execCommand("+splitBlockquote",c))a.preventDefault(),a.stopPropagation();
z.tG||c.removeNode(!0);z.D&&this.cS(a);if(z.C||z.Lg)$Q(this);else if(!b&&z.D){if(b=c=z.KB(this.G))a:{for(b=c.Zb();b;b=b.parentNode)if(lQ(b)){b="BLOCKQUOTE"==b.tagName;break a}b=!1}if(b){b=z.iB(this);d=b.createElement("BR");c.insertNode(d,!0);if(c=lQ(d.parentNode)){for(c=d.nextSibling;c&&3==c.nodeType&&!c.nodeValue;)c=c.nextSibling;c=!c}c&&z.cf(b.createElement("BR"),d);z.Xu(d,!1);a.preventDefault()}}this.G.Cf()}else z.B&&46==a.keyCode&&(b=z.KB(this.G),b.isCollapsed()&&(c=b.ka(),1==c.nodeType&&(b=c.childNodes[b.Sa()])&&
"BR"==b.tagName&&(d=z.Lu(z.Jo(new z.Iu(b,!1,!0),z.Mu)),f=b.nextSibling,c.removeChild(b),a.preventDefault(),f&&lQ(f)&&(d&&"BR"!=d.tagName&&!lQ(d)?z.Gu(d,z.Qu(d)).select():(a=z.Ku(f),z.Gu(a,0).select())))));return!1};z.e.Mt=function(a){if(z.B&&this.G.Eh)return!1;(z.C||z.Lg)&&13==a.keyCode&&$Q(this,!0);return!1};z.e.cS=z.r;z.e.bS=z.r;var aR={LI:!0,DIV:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0};var XS=new cR,YS=["click",z.B?"keypress":"keydown","keyup"];cR.prototype.g=function(a,b,c,d,f){function g(a){var c=z.cd(b),f=z.lf(a.target)?a.target.getAttribute("role")||null:null;"click"==a.type&&z.Tc(a)?c.call(d,a):13!=a.keyCode&&3!=a.keyCode||"keyup"==a.type?32!=a.keyCode||"keyup"!=a.type||"button"!=f&&"tab"!=f||(c.call(d,a),a.preventDefault()):(a.type="keypress",c.call(d,a))}g.Ek=b;g.Hv=d;f?f.g(a,YS,g,c):z.G(a,YS,g,c)};
cR.prototype.pa=function(a,b,c,d,f){for(var g,h=0;g=YS[h];h++){var k;var l=a;k=g;var n=!!c;k=z.Vc(l)?l.sm(k,n):l?(l=z.ed(l))?l.sm(k,n):[]:[];for(l=0;n=k[l];l++)if(n.listener.Ek==b&&n.listener.Hv==d){f?f.pa(a,g,n.listener,c,d):z.md(a,g,n.listener,c,d);break}}};z.y(dR,z.H);dR.prototype.yh=function(){return this.Mc?this.Mc.clone():null};dR.prototype.D=function(){dR.v.D.call(this);this.$A&&(z.nd(this.$A),this.$A=null);this.Mc=this.vw=null};dR.prototype.Rz=function(){var a=z.Qe(this.vw);z.Do(a,this.Mc)||(this.Mc=a,this.dispatchEvent("resize"))};z.y(eR,z.H);var fR="tr_bubble";z.e=eR.prototype;z.e.D=function(){eR.v.D.call(this);z.N(this.Ud);this.Ud=null;this.U.dispose();this.U=null;this.QD.dispose();this.QD=null};z.e.S=function(){return this.qo};z.e.Zb=function(){return this.Ud};z.e.aT=function(){this.W()&&this.ga()};z.e.nn=function(a){this.Qg.nn(a)};z.e.GF=function(){this.Qg.F(!1)};z.e.GS=function(){for(var a in this.Ld)z.N(this.Ld[a].element);this.Ld={};z.Cg(this.Ud,"tr_multi_bubble");this.U.removeAll();this.dispatchEvent("hide")};
z.e.W=function(){return this.Qg.W()};var ZS=z.C?4:2,iR=new z.Gg(ZS,0,ZS,0);eR.prototype.ga=function(){var a=null,b=!0,c;for(c in this.Ld)var d=this.Ld[c],a=d.lD,b=b&&d.aX;c=496;a=z.ch(this.Ud)!=z.ch(a);b&&(c=hR(this,a?7:5,4,9));c&496&&(c=hR(this,a?6:4,5,9));c&496&&hR(this,a?7:5,4,5)};eR.prototype.rR=z.Il;jR.prototype.S=function(){return this.element.lastChild};z.y(kR,z.hB);var nR={};z.e=kR.prototype;z.e.aj=null;z.e.QA=!1;z.e.Fd=z.hb("AbstractBubblePlugin");z.e.Mt=function(){this.W()&&this.pk();return!1};
z.e.pk=function(a,b){var c;if(a)c=a.target;else if(b)c=b;else{var d=z.KB(this.G);if(d){var f=d.Z(),g=d.ka(),h=d.xa(),k=d.Sa();z.C&&d.isCollapsed()&&f!=g&&(d=z.Gu(f,h));1==f.nodeType&&f==g&&h==k-1&&(f=f.childNodes[h],1==f.nodeType&&(c=f))}c=c||d&&d.Zb()}var l;a:{if(c){if(d=c)d="IMG"==c.nodeName&&(!!c.getAttribute("eeimg")||z.zg(c,"ee_img"));if(h=d?c:null){if(h!=this.bw||!this.aj)if(this.aj&&oR(this),c=mR(this),!gR(c,this.mz())){this.bw=h;var f=this.mz(),k=this.hH(),g=(0,z.t)(this.XP,this),n=this.xY(),
d=z.Vo(),h=new jR(c.ca,d,f,k,h,!n);c.Ld[d]=h;k=0;for(n=c.qo.childNodes.length-1;k<n;k++){var q=c.qo.childNodes[k];if(c.Ld[q.id].type>f){l=q;break}}z.cf(h.element,l||c.qo.lastChild);g(h.S());iQ(h.element,c.U);l=z.Ln(c.Ld);1==l?(c.U.g(c.FF,"click",c.GF).g(c.QD,"resize",c.aT).g(c.Qg,"hide",c.GS),c.Qg.F(!0),c.ga()):2==l&&z.Ag(c.Ud,"tr_multi_bubble");c.ga();this.aj=d;this.rc.g(c,"hide",this.JH);this.Vf();this.QA&&this.rc.g(c.S(),"keydown",this.oV)}l=!1;break a}}this.aj&&oR(this);l=!1}return l};
z.e.disable=function(a){if(a.Qm==z.vB){var b=nR[a.id];b&&(a==this.G&&oR(this),b.dispose(),delete nR[a.id])}};z.e.mz=function(){return""};z.e.hH=function(){return""};z.e.xY=z.Gl;z.e.Vf=z.r;z.e.GP=z.r;z.e.JH=function(){this.aj=this.bw=null;this.rc.removeAll();this.GP()};z.e.Oz=function(a){if(this.QA&&this.W()&&9==a.keyCode&&!a.shiftKey){var b=mR(this).S();if(b=z.L("tr_bubble_tabbable",b))return b.focus(),a.preventDefault(),!0}return!1};
z.e.oV=function(a){if(this.W()&&9==a.keyCode){var b=mR(this).S(),b=z.Co("tr_bubble_tabbable",b);(a.shiftKey?b[0]:z.jb(b))==a.target&&(this.G.focus(),a.preventDefault())}};z.e.W=function(){return!!this.aj};z.e.ga=function(){var a=mR(this);a&&a.ga()};
z.e.Ps=function(a,b,c,d){b=this.ca.B("SPAN",{className:"tr_bubble_link"},b);this.QA&&(b.hasAttribute("tabindex")||b.setAttribute("tabindex",0),z.Ag(b,"tr_bubble_tabbable"));b.setAttribute("role","link");d?d.appendChild(b):(d=this.ca.m(a))&&z.Bo(b,d);b.id=a;iQ(b,this.rc);c&&(a=this.rc,XS.g(b,c,void 0,a.ea||a,a));return b};z.y(pR,kR);var $S=z.w("Equation:"),aT=z.w("Edit"),bT=z.w("Remove");z.e=pR.prototype;z.e.Fd=function(){return"EquationBubble"};z.e.XP=function(a){a.appendChild(a.ownerDocument.createTextNode($S+" "));this.Ps("ee_bubble_edit",aT,this.BQ,a);a.appendChild(a.ownerDocument.createTextNode($S+" - "));this.Ps("ee_remove_remove",bT,this.yX,a)};z.e.mz=function(){return"IMG"};z.e.hH=function(){return z.w("Equation")};z.e.yX=function(){this.G.Ii();z.N(this.bw);oR(this);this.G.Cf()};
z.e.BQ=function(){var a=this.bw;oR(this);this.G.execCommand("+equation",a)};z.y(qR,z.Lc);qR.prototype.type="ok";z.y(rR,z.Lc);z.y(sR,z.Q);sR.prototype.qk="";sR.prototype.F=function(a){z.P(this.m(),a)};z.y(tR,z.QE);z.e=tR.prototype;z.e.Si=function(){return this.hb};z.e.mm=function(a){return 0<=a&&a<this.Xn.length?this.Xn[a]:null};z.e.Nf=function(a){tR.v.Nf.call(this,a);this.Og.dispatchEvent(new vR(cT,this))};z.e.ym=function(a){tR.v.ym.call(this,a);a.relatedTarget&&!z.nf(this.m(),a.relatedTarget)&&this.Og.Us()};z.e.Gd=function(a){tR.v.Gd.call(this,a);a.relatedTarget&&!z.nf(this.m(),a.relatedTarget)&&this.Og.ty.stop()};var cT="a";vR.prototype.vz=function(){return this.NW};z.y(uR,z.IE);z.ka(uR);
uR.prototype.V=function(){return"ee-palette"};z.y(wR,sR);z.e=wR.prototype;z.e.cJ="";z.e.Tx=0;
z.e.B=function(){var a=z.w("TeX 公式"),b=z.w("预览"),c=z.w("了解更多"),d=this.ca,c=d.B("DIV",{style:"display: none;"},d.B("SPAN",{"class":"ee-section-title ee-section-title-floating"},a),this.qk?d.B("A",{id:"ee-section-learn-more",target:"_blank",href:this.qk},c):null,d.B("DIV",{style:"clear: both;"}),a=this.GT=d.B("DIV",{style:"position: relative"}));this.Og.setActive("mn").render(a);a.appendChild(d.B("DIV",{style:"clear:both"}));var f=this.gi=d.B("textarea",{"class":"ee-tex",dir:"ltr"});a.appendChild(f);
a.appendChild(d.B("DIV",{"class":"ee-section-title"},b));b=this.eX=d.B("DIV",{"class":"ee-preview-container"});a.appendChild(b);this.h=c};z.e.C=function(){this.fM=new z.gE(this.gi);z.G(this.fM,"input",this.LH,!1,this);this.o().g(this.gi,"keydown",this.LH);this.o().g(this.Og,cT,this.FS)};z.e.F=function(a){wR.v.F.call(this,a);a&&z.vd(this.$Q,0,this)};z.e.$Q=function(){this.gi.focus();z.qs(this.gi,this.gi.value.length)};z.e.LH=function(){this.Tx++;z.vd((0,z.t)(this.QS,this,this.Tx),500)};
z.e.QS=function(a){a==this.Tx&&xR(this)};z.e.FS=function(a){var b=a.vz(),c=this.Og,d=c.Yn;a=this.gi;if("mn"==b.Si()){var f=b.$a,f=-1!=f?b.mm(f):null;if(d!=b&&d.Si()==f){c.yH();return}f&&(b=this.Og.setActive(f),b.m()||b.render(this.GT),b=b.m(),z.Qg(b,0,-b.clientHeight))}else{d=this.Og.Yn;f=d.mm(d.$a);if(!f)return;z.vd((0,z.t)(this.NT,this,f+" "),0)}a.focus()};z.e.NT=function(a){var b=this.gi,c=z.ns(b)[0],d=b.value,d=d.substring(0,c)+a+d.substring(c);b.value=d;z.qs(b,c+a.length);xR(this)};z.e.qm=function(){return this.gi.value};
z.e.JC=function(a){this.gi.value=a;xR(this)};z.e.D=function(){this.fM.dispose();this.Og=null;wR.v.D.call(this)};z.y(yR,z.Q);z.e=yR.prototype;z.e.hi=null;z.e.B=function(){yR.v.B.call(this);this.Ns()};z.e.Ns=function(){var a=this.m();this.hi=new wR(this.PF,this.qk,this.ca);this.K(this.hi);this.hi.render(a);this.hi.F(!0)};z.e.T=function(a){this.h=a;this.Ns()};z.e.qm=function(){return this.hi.qm()};z.e.JC=function(a){this.hi.JC(a)};
z.e.uz=function(){var a=this.qm(),b=a?nQ(a):"";return b?'\x3cimg src\x3d"'+b+'" alt\x3d"'+z.Ma(a)+'" class\x3d"ee_img tr_noresize" eeimg\x3d"1" style\x3d"vertical-align: middle"\x3e':""};z.e.isValid=function(){return 1024<this.qm().length};z.e.F=function(a){this.hi.F(a)};z.e.D=function(){this.hi&&this.hi.dispose();this.PF=null;yR.v.D.call(this)};z.y(zR,z.MF);zR.prototype.hy=function(){var a=new z.NF(this),b=z.w("公式编辑器"),c=z.w("插入公式"),d=z.w("保存修改"),f=z.w("取消"),c=this.$j.qm()?d:c;z.OF(z.PF(a.La(b).aa(this.$j.m()),f),c);return z.QF(a)};zR.prototype.Do=function(){if(this.$j.isValid())return null;var a=this.$j.uz();return new qR(a)};zR.prototype.zB=function(a){this.UJ||(this.UJ=this.xt("ok"));this.UJ.disabled=!a.isValid};z.y(AR,tR);z.y(BR,tR);z.y(CR,tR);z.y(DR,tR);z.y(ER,tR);ER.prototype.F=function(a,b){return ER.v.F.call(this,!0,b)};z.y(FR,uR);z.ka(FR);FR.prototype.V=function(){return"ee-menu-palette"};z.y(GR,tR);z.y(HR,z.H);z.e=HR.prototype;z.e.vz=function(a){var b=this.AK,c=b[a];if(!c){switch(a){case "mn":c=new ER(this);break;case "g":c=new CR(this);break;case "s":c=new GR(this);break;case "c":c=new BR(this);break;case "m":c=new DR(this);break;case "a":c=new AR(this);break;default:throw Error("Invalid palette type!");}b[a]=c}return c};z.e.setActive=function(a){var b=this.Yn;b&&b.F(!1);this.Yn=b=this.vz(a);b.F(!0);return b};z.e.Us=function(){this.ty.start()};z.e.yH=function(){this.setActive("mn")};
z.e.L=function(){return this.zQ};z.e.D=function(){HR.v.D.call(this);this.AK=this.Yn=null};z.y(IR,z.RF);z.e=IR.prototype;z.e.Fd=z.hb("EquationEditorPlugin");z.e.gy=function(a,b){var c=b||null,d;c?(d=c.getAttribute("alt"),d||(d=(d=c.getAttribute("src"))?z.be(d,"tex")||"":"")):d="";this.yK=c;c={};c.MW=new HR(a);c=new zR(c,a,d,this.qk);c.addEventListener("ok",this.jp,!1,this);return c};z.e.enable=function(a){IR.v.enable.call(this,a);this.isEnabled(a)&&(this.gQ=z.G(a.m(),"dblclick",(0,z.t)(this.PR,this),!1,this))};z.e.disable=function(a){IR.v.disable.call(this,a);this.isEnabled(a)||z.nd(this.gQ)};
z.e.PR=function(a){(a=a.target)&&"IMG"===a.nodeName&&a.getAttribute("eeimg")&&this.execCommand("+equation",a)};z.e.jp=function(a){z.SF(this);this.G.Ii();a=z.Ze(z.iB(this).Ra,a.PQ);if(this.yK)z.Bo(a,this.yK);else{var b=z.KB(this.G);b.isCollapsed()||b.Yf();a=b.insertNode(a,!1)}z.Xu(a,!1);this.G.Cf()};z.y(JR,z.hB);JR.prototype.Nt=function(a){return z.B&&this.G.Eh?!1:9!=a.keyCode||a.metaKey||a.ctrlKey?!1:LR(this,a)};z.y(KR,JR);KR.prototype.Fd=function(){return"ListTabHandler"};z.y(MR,z.hB);z.e=MR.prototype;z.e.Fd=z.hb("LoremIpsum");z.e.as=z.Hl;z.e.Er=!1;z.e.queryCommandValue=function(a){return"usinglorem"==a&&this.Er};
z.e.execCommand=function(a,b){if("clearlorem"==a){var c=!!b,d=this.G;if(this.Er&&!d.Eh){var f=d.m();f||(f=d.Wc);this.Er=!1;f.style.fontStyle=this.bV;d.ge(!0,null,!0);c&&d.Kc()&&(z.D?(z.Ke(d.m()).body.focus(),d.wg()):z.Lg&&z.QB(d))}}else"updatelorem"==a&&(c=this.G,this.Er||c.Eh||z.cH==c.id||((d=c.m())||(d=c.Wc),z.Ou(d)&&(this.Er=!0,this.bV=d.style.fontStyle,d.style.fontStyle="italic",c.ge(!0,this.PU,!0))))};z.e.ff=function(a){return"clearlorem"==a||"updatelorem"==a||"usinglorem"==a};z.y(NR,z.H);z.y(OR,z.H);z.e=OR.prototype;z.e.bu=null;z.e.BD=function(){PR(this,this.ie,this.Zk)};z.e.mC=function(){PR(this,this.Zk,this.ie)};z.e.qh=function(){if(!this.bu&&0!=this.jv.length){var a=this.jv.shift();this.dispatchEvent({type:a.type,state:a.state})&&(a.state.YO?(this.bu=z.G(a.state,"action_completed",this.VQ,!1,this),a.eH.call(a.state)):(a.eH.call(a.state),this.qh()))}};z.e.VQ=function(){z.nd(this.bu);this.bu=null;this.qh()};z.y(QR,z.hB);QR.prototype.up=null;var dT=z.Lo({X_:"+undo",M_:"+redo"});z.e=QR.prototype;z.e.ff=function(a){return a in dT};z.e.CM=function(a){this.disable(a);this.G=null};z.e.enable=function(a){if(!this.isEnabled(a)){z.NB(a);var b=new z.xd(this);z.B||b.g(a,"beforechange",this.AR);b.g(a,z.rB,this.KR);b.g(a,"blur",this.Cz);this.ak[a.Ch]=b;RR(this,a)}};z.e.disable=function(a){z.NB(a);var b=this.ak[a.Ch];b&&(b.dispose(),delete this.ak[a.Ch]);this.Io[a.Ch]&&delete this.Io[a.Ch]};z.e.isEnabled=function(a){return!!this.ak[a.Ch]};
z.e.D=function(){QR.v.D.call(this);for(var a in this.ak)this.ak[a].dispose(),delete this.ak[a];this.G=null;this.gg&&(this.gg.dispose(),delete this.gg)};z.e.Fd=function(){return"UndoRedo"};z.e.execCommand=function(a){"+undo"==a?this.gg.BD():"+redo"==a&&this.gg.mC()};z.e.queryCommandValue=function(a){var b=null;"+undo"==a?b=0<this.gg.ie.length:"+redo"==a&&(b=0<this.gg.Zk.length);return b};z.e.vQ=function(){this.G.dispatchEvent({type:"cvc",PP:["+redo","+undo"]})};
z.e.NX=function(a,b,c){var d=this.G;if(d){z.MB(d,!0,!0);try{d.Ii();d.execCommand("clearlorem",!0);z.Su(d.m(),b);c&&c.select();var f=this.G;d.focus();f&&f.Ch!=a.Po&&f.execCommand("updatelorem");var g=this.Io[a.Po];g.rj=b;g.zM=c}catch(h){}finally{this.up=a,d.Cf(),z.LB(d)}}};
z.e.Nt=function(a,b,c){if(c){var d;"z"==b?d=a.shiftKey?"+redo":"+undo":"y"==b&&(d="+redo");if(d)return"+undo"==d?(a=this.gg,a=a.ie[a.ie.length-1]):(a=this.gg,a=a.Zk[a.Zk.length-1]),a&&a.Po?this.G.execCommand(d):this.execCommand(d),!0}return!1};z.e.AR=function(a){if(!this.up){a=a.target;var b=a.Ch;this.uI!=b&&(this.uI=b,RR(this,a))}};z.e.KR=function(a){this.up?(a=this.up,this.up=null,a.dispatchEvent("action_completed")):RR(this,a.target)};z.e.Cz=function(a){(a=a.target)&&z.NB(a)};z.y(TR,NR);
TR.prototype.BD=function(){this.kL(this,this.rj,this.zM)};TR.prototype.mC=function(){this.kL(this,this.nC,this.rX)};TR.prototype.equals=function(a){return this.Po==a.Po&&this.rj==a.rj&&this.nC==a.nC};SR.prototype.isValid=function(){return this.pu};SR.prototype.toString=function(){return z.tG?"W3C:"+this.Ea.toString()+"\n"+this.aD+":"+this.Ca.toString()+"\n"+this.My:"IE:"+this.Ea+","+this.Ca};SR.prototype.select=function(){var a=this.Ye(this.te.m());a&&(z.sG&&this.te.m().focus(),z.Eu(a).select())};
SR.prototype.Ye=function(a){if(z.tG){var b=YQ(this.Ea,a);a=YQ(this.Ca,a);return b&&a?z.nu(b,this.aD,a,this.My).we():null}b=a.ownerDocument.body.createTextRange();b.moveToElementText(a);b.collapse(!0);b.moveEnd("character",this.Ca);b.moveStart("character",this.Ea);return b};z.y(VR,z.H);z.e=VR.prototype;z.e.o=function(){return this.ea};z.e.qz=function(){return this.te};z.e.W=function(){return this.Nb.W()};z.e.F=function(a){this.Nb.F(a)};z.e.isEnabled=function(){return this.Nb.isEnabled()};z.e.gb=function(a){this.Nb.gb(a)};z.e.blur=function(){this.Nb.od(null)};z.e.D=function(){VR.v.D.call(this);this.ea&&(this.ea.dispose(),delete this.ea);this.Nb&&(this.Nb.dispose(),delete this.Nb);delete this.te;delete this.fC};
z.e.IZ=function(a){if(this.Nb.isEnabled()&&this.dispatchEvent("change")){var b;try{b=this.te.queryCommandValue(a.PP||this.fC)}catch(f){b={}}a=b;for(var c in a)if(b=z.yh(this.Nb,c)){var d=a[c];b.tj?b.tj(d):b.yc(!!d)}}};z.e.vR=function(a){var b=a.target.xe();this.te.execCommand(b,a.target.X())};z.y(XR,z.Tz);z.Ip("goog-toolbar-separator",function(){return new XR});z.y(YR,z.hB);z.e=YR.prototype;z.e.defaults={F0:z.r};z.e.Fd=z.hb("FastUpload");
z.e.enable=function(a){if(!this.isEnabled(a)&&(window.URL||window.webkitURL)&&window.FileReader&&window.FormData&&window.document.addEventListener){window.$.fn.draghover=function(){return this.each(function(){var a=(0,window.$)(),b=(0,window.$)(this),f=!0;b.on("dragenter",function(g){g=g.originalEvent;0===a.size()&&f&&z.rb(g.dataTransfer.types,"Files")&&b.trigger("draghoverstart",g);a=a.add(g.target)});b.on("dragleave",function(g){(0,window.setTimeout)(function(){a=a.not(g.target);0===a.size()&&f&&
b.trigger("draghoverend",g)},1)});b.on("dragstart",function(){f=!1});b.on("drop dragend",function(){a=(0,window.$)();b.trigger("draghoverend");f=!0})})};this.$D=(0,window.$)(this.G.m());var b=this.nN=ZR(this);new z.xd(this);a.m().addEventListener("paste",(0,z.t)(this.Qz,this));window.document.addEventListener("dragover",(0,z.t)(this.ZR,this),!1);b.on("dragover",(0,z.t)(this.YR,this));b.get(0).addEventListener("drop",(0,z.t)(this.Kt,this),!1);(0,window.$)(window).draghover().on({draghoverstart:(0,z.t)(this.AH,
this),draghoverend:(0,z.t)(this.$R,this)});b.draghover().on({draghoverstart:(0,z.t)(this.RR,this),draghoverend:(0,z.t)(this.AH,this)})}};z.e.ZR=function(a){z.rb(a.dataTransfer.types,"Files")&&(a.dataTransfer.dropEffect="none",a.preventDefault())};z.e.YR=function(a){a=a.originalEvent;a.dataTransfer.dropEffect="copy";a.preventDefault();a.stopPropagation()};z.e.AH=function(a){a.preventDefault();a.stopPropagation();aS(this,1)};z.e.RR=function(a){aS(this,2);a.stopPropagation()};
z.e.$R=function(a){a.preventDefault();aS(this,0)};z.e.Qz=function(a){var b=this;a.clipboardData&&z.rb(a.clipboardData.types,"Files")&&1===a.clipboardData.items.length&&z.A(a.clipboardData.items,function(c){-1<c.type.indexOf("image")&&(bS(b,c.getAsFile()),a.preventDefault())})};
z.e.Kt=function(a){var b=this;b.G.execCommand("clearlorem");var c=a.dataTransfer.files;a.preventDefault();var d=[];z.A(c,function(a){-1<a.type.indexOf("image")?(bS(b,a),d.push(!0)):d.push(!1)});z.Mn(d,function(a){return!a})&&z.T.message("文件类型不支持！");aS(b,0)};var eT={};
(function(){function a(a,c,d){function q(a){z.ff(a)}function ca(b,c){for(;b!==a;){if(c(b))return b;b=b.parentNode}return null}function Va(a){return a.tagName&&a.tagName===c}if(!a)throw"Missing Editable Container";c||(c="blockquote");c=c.toUpperCase();var Sa=z.Cu();if(function(b){return b&&g(a,z.Lt(b))&&g(a,z.Nt(b))}(Sa)){var Aa=h(Sa),ua=k(Sa),Jd=Sa.Zb(),ti=ca(Jd,Va),we=z.nb(ua,function(a,b){1===b.nodeType&&(Va(b)?a.push(b):a.push.apply(a,z.vb(b.getElementsByTagName(c))));return a},[]),Ud;if(ti){if(d)return n.Xw;
z.ff(ti)}else if(we.length){if(d)return n.Xw;z.A(we,q)}else{if(d)return n.vE;if(d=ca(Jd,function(a){return z.rb(l,a.tagName.toLowerCase())}))Ud=window.document.createElement(c),d.parentNode.insertBefore(Ud,d),Ud.appendChild(d);else if(Sa.Z()!==Sa.ka())Ud=window.document.createElement(c),ua[0].parentNode.insertBefore(Ud,ua[0]),z.A(ua,function(a){Ud.appendChild(a)});else return f(a,c)}b(a,Aa)}else if(d)return n.vE}function b(a,b){if(b){var c=function(b,c){return b&&g(a,b)&&z.Qu(b)>=c};c(b.Z(),b.xa())&&
c(b.ka(),b.Sa())&&b.select()}}function c(a){return a&&"BR"===a.tagName||lQ(a)||z.Uu(a)}function d(a){a=z.wf(a,function(a){a=a.parentNode;return lQ(a)||z.Uu(a)},!0);var b=oQ(new z.Iu(a,!0,!0),z.Qo(c));a=oQ(new z.Iu(a,!1,!1),z.Qo(c));return z.Pd(b).reverse().concat(z.Pd(a))}function f(a,b){if(q.fO)window.document.execCommand("formatBlock",!1,b);else{var c=z.Cu(),f=c.Ic();if(z.lf(f)&&z.Ou(f))c=window.document.createElement(b),f===a?f.appendChild(c):z.Bo(c,f),(z.D||z.B)&&c.appendChild(window.document.createElement("br")),
z.Wu(c);else if(f=c.ka(),f=d(f),f.length){var c=window.document.createElement(b),g=z.jb(f),h=g.nextSibling;h&&h&&"BR"===h.tagName&&z.N(h);z.df(c,g);z.af(c,f);(z.D||z.B)&&c.appendChild(window.document.createElement("br"));z.Xu(c.lastChild)}}}function g(a,b){return 3===a.nodeType?a===b:a.contains(3===b.nodeType?b.parentNode:b)}function h(a){return aQ(a.Z(),a.xa(),a.ka(),a.Sa())}function k(a){function b(a){return!(a.previousSibling&&g(a.previousSibling,h))}function c(a){return f!==d&&!g(a,f)}if(a.isCollapsed())return[];
var d=a.Ic(),f=a.Z(),h=a.ka();a=d.childNodes;return z.Pd(1===a.length?a:oQ(pQ(a,c),b))}var l=["ul","ol","dl","table"],n={Xw:1,vE:0},q=eT;q.fO=!z.C;q.toggle=a;q.getState=function(b,c){return a(b,c,!0)};q.aO=n})();z.y(cS,z.hB);z.e=cS.prototype;z.e.Fd=z.hb("Blockquote");z.e.ff=function(a){return"+blockquote"===a};z.e.Ef=function(a){this.ff(a)&&eT.toggle(this.G.m())};z.e.queryCommandValue=function(){return eT.aO.Xw===eT.getState(this.G.m())};z.e.Oz=function(a){if(13===a.keyCode)return this.Kz(a)};z.e.PC=function(a,b){return eS(a,b).PC};
z.e.Kz=function(a){var b=z.KB(this.G);if(b.isCollapsed()){var c;a:{c=b.ka();for(var d=this.G.Ka;c!==d;){if("BLOCKQUOTE"===c.tagName)break a;c=c.parentNode}c=void 0}if(c&&(b=eS(c,b),b.PC)){a.preventDefault();a=window.document.createElement("div");z.df(a,c);if(z.D||z.B)c=c.nextSibling,(c=dS(c)&&c)||(c=window.document.createElement("br")),a.appendChild(c);z.Gu(a,0).select();b.QJ&&z.N(b.QJ)}}};z.$H["+blockquote"]={tb:!0,na:"引用内容",Ba:"+blockquote",Wa:"tr-icon tr-blockquote",factory:z.xF};z.y(gS,z.Q);
var jS=[["ABAP","abap"],["ABNF","abnf"],["ActionScript 3","as3"],["ActionScript","as"],["Ada","ada"],["ADL","adl"],["Agda","agda"],["Alloy","alloy"],["AmbientTalk","at"],["ANTLR","antlr"],["ApacheConf","apacheconf"],["APL","apl"],["AppleScript","applescript"],["Arduino","arduino"],["AspectJ","aspectj"],["aspx-cs","aspx-cs"],["aspx-vb","aspx-vb"],["Asymptote","asy"],["autohotkey","ahk"],["AutoIt","autoit"],["Awk","awk"],["Base Makefile","basemake"],["Bash Session","console"],["Bash","bash"],["Batchfile",
"bat"],["BBCode","bbcode"],["BC","bc"],["Befunge","befunge"],["BlitzBasic","blitzbasic"],["BlitzMax","blitzmax"],["BNF","bnf"],["Boo","boo"],["Boogie","boogie"],["Brainfuck","brainfuck"],["Bro","bro"],["BUGS","bugs"],["C","c"],["C#","csharp"],["C++","cpp"],["c-objdump","c-objdump"],["ca65 assembler","ca65"],["cADL","cadl"],["CAmkES","camkes"],["CBM BASIC V2","cbmbas"],["Ceylon","ceylon"],["CFEngine3","cfengine3"],["cfstatement","cfs"],["ChaiScript","chai"],["Chapel","chapel"],["Cheetah","cheetah"],
["Cirru","cirru"],["Clay","clay"],["Clojure","clojure"],["ClojureScript","clojurescript"],["CMake","cmake"],["COBOL","cobol"],["COBOLFree","cobolfree"],["CoffeeScript","coffee-script"],["Coldfusion CFC","cfc"],["Coldfusion HTML","cfm"],["Common Lisp","common-lisp"],["Component Pascal","componentpascal"],["Coq","coq"],["cpp-objdump","cpp-objdump"],["CPSA","cpsa"],["Crmsh","crmsh"],["Croc","croc"],["Cryptol","cryptol"],["Csound Document","csound-document"],["Csound Orchestra","csound"],["Csound Score",
"csound-score"],["CSS","css"],["CUDA","cuda"],["Cypher","cypher"],["Cython","cython"],["D","d"],["d-objdump","d-objdump"],["Darcs Patch","dpatch"],["Dart","dart"],["Debian Control file","control"],["Debian Sourcelist","sourceslist"],["Delphi","delphi"],["dg","dg"],["Diff","diff"],["Django/Jinja","django"],["Docker","docker"],["DTD","dtd"],["Duel","duel"],["Dylan session","dylan-console"],["Dylan","dylan"],["DylanLID","dylan-lid"],["Earl Grey","earl-grey"],["Easytrieve","easytrieve"],["EBNF","ebnf"],
["eC","ec"],["ECL","ecl"],["Eiffel","eiffel"],["Elixir iex session","iex"],["Elixir","elixir"],["Elm","elm"],["EmacsLisp","emacs"],["Embedded Ragel","ragel-em"],["ERB","erb"],["Erlang erl session","erl"],["Erlang","erlang"],["Evoque","evoque"],["Ezhil","ezhil"],["Factor","factor"],["Fancy","fancy"],["Fantom","fan"],["Felix","felix"],["Fish","fish"],["Fortran","fortran"],["FortranFixed","fortranfixed"],["FoxPro","foxpro"],["FSharp","fsharp"],["GAP","gap"],["GAS","gas"],["Genshi Text","genshitext"],
["Genshi","genshi"],["Gettext Catalog","pot"],["Gherkin","cucumber"],["GLSL","glsl"],["Gnuplot","gnuplot"],["Go","go"],["Golo","golo"],["GoodData-CL","gooddata-cl"],["Gosu Template","gst"],["Gosu","gosu"],["Groff","groff"],["Groovy","groovy"],["Haml","haml"],["Handlebars","handlebars"],["Haskell","haskell"],["Haxe","hx"],["Hexdump","hexdump"],["HTML","html"],["HTML+Django/Jinja","html+django"],["HTML+Handlebars","html+handlebars"],["HTTP","http"],["Hxml","haxeml"],["Hy","hylang"],["Hybris","hybris"],
["IDL","idl"],["Idris","idris"],["Igor","igor"],["Inform 6 template","i6t"],["Inform 6","inform6"],["Inform 7","inform7"],["INI","ini"],["Io","io"],["Ioke","ioke"],["IRC logs","irc"],["Isabelle","isabelle"],["J","j"],["Jade","jade"],["JAGS","jags"],["Jasmin","jasmin"],["Java Server Page","jsp"],["Java","java"],["JavaScript","js"],["JCL","jcl"],["JSON","json"],["JSON-LD","jsonld"],["Julia console","jlcon"],["Julia","julia"],["Kal","kal"],["Kconfig","kconfig"],["Koka","koka"],["Kotlin","kotlin"],["Lasso",
"lasso"],["Lean","lean"],["LessCss","less"],["Lighttpd configuration file","lighty"],["Limbo","limbo"],["liquid","liquid"],["Literate Agda","lagda"],["Literate Cryptol","lcry"],["Literate Haskell","lhs"],["Literate Idris","lidr"],["LiveScript","live-script"],["LLVM","llvm"],["Logos","logos"],["Logtalk","logtalk"],["LSL","lsl"],["Lua","lua"],["Makefile","make"],["Mako","mako"],["MAQL","maql"],["Mask","mask"],["Mason","mason"],["Mathematica","mathematica"],["Matlab session","matlabsession"],["Matlab",
"matlab"],["MiniD","minid"],["Modelica","modelica"],["Modula-2","modula2"],["MoinMoin/Trac Wiki markup","trac-wiki"],["Monkey","monkey"],["MOOCode","moocode"],["MoonScript","moon"],["mozhashpreproc","mozhashpreproc"],["mozpercentpreproc","mozpercentpreproc"],["MQL","mql"],["Mscgen","mscgen"],["MSDOS Session","doscon"],["MuPAD","mupad"],["MXML","mxml"],["Myghty","myghty"],["MySQL","mysql"],["NASM","nasm"],["Nemerle","nemerle"],["nesC","nesc"],["NewLisp","newlisp"],["Newspeak","newspeak"],["Nginx configuration file",
"nginx"],["Nimrod","nimrod"],["Nit","nit"],["Nix","nixos"],["NSIS","nsis"],["NumPy","numpy"],["objdump","objdump"],["objdump-nasm","objdump-nasm"],["Objective-C","objective-c"],["Objective-C++","objective-c++"],["Objective-J","objective-j"],["OCaml","ocaml"],["Octave","octave"],["ODIN","odin"],["Ooc","ooc"],["Opa","opa"],["OpenEdge ABL","openedge"],["PacmanConf","pacmanconf"],["Pan","pan"],["ParaSail","parasail"],["Pawn","pawn"],["Perl","perl"],["Perl6","perl6"],["PHP","php"],["Pig","pig"],["Pike",
"pike"],["PkgConfig","pkgconfig"],["PL/pgSQL","plpgsql"],["PostgreSQL console (psql)","psql"],["PostgreSQL SQL dialect","postgresql"],["PostScript","postscript"],["POVRay","pov"],["PowerShell Session","ps1con"],["PowerShell","powershell"],["Praat","praat"],["Prolog","prolog"],["Properties","properties"],["Protocol Buffer","protobuf"],["Puppet","puppet"],["PyPy Log","pypylog"],["Python 3","python3"],["Python 3.0 Traceback","py3tb"],["Python console session","pycon"],["Python Traceback","pytb"],["Python",
"python"],["QBasic","qbasic"],["QML","qml"],["QVTO","qvto"],["Racket","racket"],["Ragel","ragel"],["RConsole","rconsole"],["Rd","rd"],["REBOL","rebol"],["Red","red"],["Redcode","redcode"],["reg","registry"],["ResourceBundle","resource"],["reStructuredText","rst"],["Rexx","rexx"],["RHTML","rhtml"],["Roboconf Graph","roboconf-graph"],["Roboconf Instances","roboconf-instances"],["RobotFramework","robotframework"],["RPMSpec","spec"],["RQL","rql"],["RSL","rsl"],["Ruby irb session","rbcon"],["Ruby","rb"],
["Rust","rust"],["S","splus"],["Sass","sass"],["Scala","scala"],["Scalate Server Page","ssp"],["Scaml","scaml"],["Scheme","scheme"],["Scilab","scilab"],["SCSS","scss"],["Shen","shen"],["Slim","slim"],["Smali","smali"],["Smalltalk","smalltalk"],["Smarty","smarty"],["Snobol","snobol"],["SourcePawn","sp"],["SPARQL","sparql"],["SQL","sql"],["sqlite3con","sqlite3"],["SquidConf","squidconf"],["Stan","stan"],["Standard ML","sml"],["SuperCollider","sc"],["Swift","swift"],["SWIG","swig"],["systemverilog",
"systemverilog"],["TADS 3","tads3"],["TAP","tap"],["Tcl","tcl"],["Tcsh Session","tcshcon"],["Tcsh","tcsh"],["Tea","tea"],["Termcap","termcap"],["Terminfo","terminfo"],["Terraform","terraform"],["TeX","tex"],["Text only","text"],["Thrift","thrift"],["Todotxt","todotxt"],["TrafficScript","rts"],["Treetop","treetop"],["Turtle","turtle"],["Twig","twig"],["TypeScript","ts"],["UrbiScript","urbiscript"],["Vala","vala"],["VB.net","vb.net"],["VCTreeStatus","vctreestatus"],["Velocity","velocity"],["verilog",
"verilog"],["VGL","vgl"],["vhdl","vhdl"],["VimL","vim"],["X10","x10"],["XML","xml"],["XQuery","xquery"],["XSLT","xslt"],["Xtend","xtend"],["XUL+mozpreproc","xul+mozpreproc"],["YAML","yaml"],["YAML+Jinja","yaml+jinja"],["Zephir","zephir"]],lS=z.mb(jS,hS);z.e=gS.prototype;z.e.defaults={iY:"lang-select",Fs:"collapsed",tU:"lang-list",BW:"lang-option",jh:"active",BF:"checked"};z.e.D=function(){gS.v.D.call(this);this.o().dispose();this.Y.dispose();z.N(this.h);this.rt=this.gw=this.h=null};
z.e.B=function(){var a=this.J;this.h=z.M("div",{innerHTML:this.template,className:[a.iY,a.Fs].join(" ")})};z.e.template='\x3cdiv class\x3d"title-button"\x3e选择语言\x3c/div\x3e\x3ci class\x3d"zg-icon zg-icon-double-arrow"\x3e\x3c/i\x3e\x3cdiv class\x3d"input-wrapper"\x3e\x3cinput class\x3d"filter-input zg-form-text-input" placeholder\x3d"搜索语言"\x3e\x3c/div\x3e';
z.e.C=function(){gS.v.C.call(this);this.gw=z.L("title-button",this.h);this.rt=z.L("filter-input",this.h);z.fo(this.gw,!0);mS(this,this.rt,this.h);this.o().g(this.h,"click",this.vm).g(this.gw,"click",this.RS)};z.e.X=function(){return this.Ie};z.e.Da=function(a){var b=a&&z.pb(lS,function(b){return b.value===a});b&&(this.bl(b.label),this.dispatchEvent({type:"change",AW:b}));this.Ie=a};
z.e.vm=function(a){var b=this.Y,c=b.M.m();c&&window.document.activeElement!==this.rt&&!c.contains(a.target)&&(a.preventDefault(),a.stopPropagation(),z.ls(b))};z.e.RS=function(){this.isCollapsed()&&this.lj(!1)};z.e.wt=function(){return this.Y};z.e.isCollapsed=function(){return z.S.has(this.h,this.J.Fs)};z.e.lj=function(a){if(this.isCollapsed()!==a){var b=this.rt,c=this.J;a?z.S.add(this.h,c.Fs):(z.S.remove(this.h,c.Fs),a=this.Y,c=a.M,a.kn(lS),c.m().scrollTop=0,c.show(),b.value="",b.focus())}};
z.e.bl=function(a){var b=this.gw;b.title=a;z.of(b,a)};z.e.GB=function(a){this.Da(a.value);this.Y.Rc()};z.y(nS,z.hB);var AS=z.D||z.Lg||z.B;z.e=nS.prototype;z.e.Fd=z.hb("CodePlugin");z.e.ff=function(a){return"+code"===a};z.e.Ef=function(a){this.ff(a)&&this.trigger()};z.e.queryCommandValue=function(){var a="1"===vS(this).state,b=this.G.bc.EnterHandler;b&&(a?b.disable(this.G):b.enable(this.G));tS(this,a);return a};z.e.defaults={hQ:""};z.e.sY=function(a){this.Nb=a;this.Uy=["toggleFullScreen"].concat("+code")};z.e.D=function(){nS.v.D.call(this);this.Nb=null};
z.e.trigger=function(){var a=vS(this),b=a.vv,c=a.code;switch(a.state){case "1":var d=!(0,z.ab)(z.uo(c)),a=z.Nu(c);d?(c.parentNode.removeChild(c),a&&z.Xu(a,!0)):(b=bQ(b),d=z.La(c.innerHTML),z.Lu(z.Jo(new z.Iu(c,!1,!0),z.Mu))&&(d="\x3cbr\x3e"+d),a&&"BR"!==a.tagName&&(d+="\x3cbr\x3e"),a=z.Ye(d),c.parentNode.replaceChild(a,c),b.restore());break;case "2":c=DS,a=(0,z.ab)(b.$d())?sS(b.Bg()):AS?"\n":"",c(this,b,a)}};
z.e.Bo=function(a,b){var c=window.document.createElement(a);c.id=z.vh(z.uh.ba());return b(c,function(){c=z.J(c.id);c.removeAttribute("id");return c})};z.e.ih=function(){var a=this.G;this.Wn=rS(this.G.Ka);z.Ac(a,this.Wn);z.G(a,"delayedchange",this.IX,!1,this);z.G(a.Ka,"paste",this.Qz,!1,this)};z.e.IX=function(){var a=this.Wn&&this.Wn.tz();a&&a.W()&&a.anchor&&a.ga()};
z.e.Qz=function(a){var b=vS(this),c=b.vv,d=b.code;if("1"===b.state)if(b=a.sc.clipboardData)b.types&&z.rb(b.types,"text/plain")&&(a.preventDefault(),b=b.getData("text/plain"),wS(c,b));else if(window.clipboardData){if(b=window.clipboardData.getData("Text"))a.preventDefault(),xS(this,c,b)}else{var f=c.xa();a=c.$d().length;var g=(d.firstChild?z.Qu(d.firstChild):0)-f-a;(0,window.setTimeout)(function(){var a=sS(d.innerHTML);z.of(d,a);a=(d.firstChild?z.Qu(d.firstChild):0)-g;d.firstChild&&z.Gu(d.firstChild,
Math.max(f,a)).select()})}};z.e.Oz=function(a){if(13===a.keyCode)return this.Kz(a);if(40===a.keyCode)return zS(this)};z.e.Kz=function(a){var b=vS(this),c=b.vv;if("1"===b.state)return a.preventDefault(),z.C?CS(this,c):window.document.queryCommandSupported("insertLineBreak")?window.document.execCommand("insertLineBreak"):(a=window.document.createTextNode("\n"),c.insertNode(a),z.Xu(a)),this.G.Cf(),!0};z.$H["+code"]={tb:!0,na:"插入代码",Ba:"+code",Wa:"tr-icon tr-code",factory:z.xF};z.y(FS,z.hB);var fT=/^(DIV|TR|LI|BLOCKQUOTE|H\d|PRE|XMP)/;z.e=FS.prototype;z.e.Fd=function(){return"RemoveFormatting"};z.e.ff=function(a){return"+removeFormat"==a};z.e.Ef=function(a){"+removeFormat"==a&&HS(this)};z.e.Nt=function(a,b,c){return c?" "==b?(this.G.execCommand("+removeFormat"),!0):!1:!1};
z.e.aL=function(a){var b=window.document.createElement("DIV");b.innerHTML=a;a=[];for(var b=[b.childNodes,0],c=[],d=0,f=[],g=0,h=0;0<=h;h-=2){for(var k=!1;0<g&&h<=f[g-1];)g--,k=!0;k&&GS(a);for(k=!1;0<d&&h<=c[d-1];)d--,k=!0;k&&GS(a);for(var k=b[h],l=b[h+1];l<k.length;){var n=k[l++],q=n.nodeName,v=this.sH(n);if(null!=v)a.push(v);else{switch(q){case "#text":n=0<d?n.nodeValue:z.Zo(n.nodeValue);n=z.Ma(n);a.push(n);continue;case "P":GS(a);GS(a);break;case "BR":GS(a);continue;case "TABLE":GS(a);f[g++]=h;
break;case "PRE":case "XMP":c[d++]=h;break;case "STYLE":case "SCRIPT":case "SELECT":continue;case "A":if(n.href&&""!=n.href){a.push("\x3ca href\x3d'");a.push(n.href);a.push("'\x3e");a.push(this.aL(n.innerHTML));a.push("\x3c/a\x3e");continue}else break;case "IMG":a.push("\x3cimg src\x3d'");a.push(n.src);a.push("'");"0"==n.border&&a.push(" border\x3d'0'");a.push("\x3e");continue;case "TD":n.previousSibling&&a.push(" ");break;case "TR":n.previousSibling&&GS(a);break;case "DIV":if(v=n.parentNode,v.firstChild==
n&&fT.test(v.tagName))break;default:fT.test(q)&&GS(a)}n=n.childNodes;0<n.length&&(b[h++]=k,b[h++]=l,k=n,l=0)}}}return a.join("").replace(/\xa0|[ \t]+/g," ")};z.e.sH=function(){return null};z.y(KS,FS);KS.prototype.sH=function(a){var b;if("IMG"!==a.nodeName)return null;b=[];b.push('\x3cimg src\x3d"');b.push(z.Ma(a.src));b.push('"');a.getAttribute("eeimg")&&a.getAttribute("alt")&&b.push(' eeimg\x3d"'+z.Ma(a.getAttribute("eeimg"))+'" alt\x3d"'+z.Ma(a.getAttribute("alt"))+'"');b.push("\x3e");return b.join("")};z.y(LS,z.MF);z.y(MS,z.Lc);z.e=LS.prototype;z.e.show=function(){LS.v.show.call(this);this.sw.focus()};z.e.hide=function(){LS.v.hide.call(this)};
z.e.hy=function(){var a=z.sm.Ln+"/upload_video",a=this.Cd.B("div","zm-img-uploader zm-img-uploader-upload-tab-selected",[this.Cd.B("div","zg-section",this.Cd.B("strong",null,"输入视频页地址：")),this.Cd.B("iframe",{id:"video_up_frame",src:"about:_blank",name:"video_up_frame",style:"visible:hidden;position:absolute;height:0;width:0;left:-9000px"}),this.aH=this.Cd.B("form",{"class":"zg-section-title",target:"video_up_frame",method:"post",enctype:"multipart/form-data",action:a},[this.sw=this.Cd.B("input",{type:"text",
"class":"zg-form-text-input",name:"upload_file_url",autocomplete:"off"}),this.zo=this.Cd.B("a",{"class":"zg-btn-blue zm-uploader-button-fix",name:"save",href:"javascript:;"},"确定"),this.Cd.B("div","zm-video-uploader-info",[this.Nh=this.Cd.B("span",{style:"display:none","class":"zm-img-uploader-loading"},"正在上传"),this.Df=this.Cd.B("span",{style:"display:none","class":"zm-img-uploader-error"},"插入视频失败，请稍后重试")])]),this.vT=this.Cd.B("div","zg-gray"),this.xo=this.Cd.B("div","zm-command",[this.Qx=this.Cd.B("a",
{href:"javascript:;"},"取消")])]);this.vT.innerHTML='我们目前支持\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://youku.com"\x3e优酷\x3c/a\x3e、\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://tudou.com"\x3e土豆\x3c/a\x3e、\x3ca href\x3d"http://video.sina.com.cn/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e新浪\x3c/a\x3e、\x3ca href\x3d"http://v.qq.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e腾讯\x3c/a\x3e、\x3ca href\x3d"http://www.56.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e56\x3c/a\x3e、\x3ca href\x3d"http://tv.sohu.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e搜狐\x3c/a\x3e、\x3ca href\x3d"http://www.iqiyi.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e爱奇艺\x3c/a\x3e视频服务。\x3cbr /\x3e请不要上传与回答问题无关的视频，详细请看 \x3ca href\x3d"http://www.zhihu.com/question/20118966" target\x3d"_blank"\x3e知乎视频使用规范\x3c/a\x3e';
this.U.g(this.Qx,"click",function(){this.fp();this.hide()}).g(this.zo,"click",this.FK).g(this.xo,"click",this.Xa).g(this.aH,"submit",function(){return NS(this,this.sw.value)}).g(z.U,"iframe_data",this.kx);this.NF=a;var b=new z.NF(this);b.La("插入视频").aa(a);a=z.QF(b);z.Rh(a,null);return a};z.e.FK=function(){if(this.sw.value){var a=z.lr(this.sw.value);a&&NS(this,a)&&(z.P(this.Nh,!0),z.P(this.Df,!1),this.aH.submit())}};z.e.Xa=function(a){"save"===(a.target&&a.target.name)&&this.FK()};
z.e.kx=function(a){z.P(this.Nh,!1);this.nj(a.Xf)};z.e.nj=function(a){a&&!a.r?(this.dispatchEvent(this.Do(a.msg[0],a.msg[1],a.msg[2],a.msg[3],a.msg[4])),this.hide()):(a=a.msg,z.P(this.Nh,!1),this.Df.innerHTML=a,z.P(this.Df,!0))};z.e.Do=function(a,b,c,d,f){return new MS(a,b,c,d,f)};z.e.D=function(){this.U.dispose();this.U=null;LS.v.D.call(this)};z.y(OS,z.RF);z.e=OS.prototype;z.e.Fd=z.hb("VideoDialogPlugin");z.e.Ef=function(a,b){var c=this.G;return c.Rf||(c.wg(),c.Rf)?OS.v.Ef.call(this,a,b):!1};
z.e.ep=function(a){OS.v.ep.call(this,a)};z.e.gy=function(a){a=new LS(a);this.U.g(a,"ok",this.jp).g(a,"cancel",this.Dz);return a};z.e.D=function(){OS.v.D.call(this);this.U.dispose()};
z.e.jp=function(a){z.SF(this);var b=z.iB(this),c=b.B("a",{"class":"video-link",href:a.KY,"data-src":a.SZ,"data-name":a.RM,"data-poster":a.poster,"data-videoid":a.RZ});z.of(c,a.RM);a=z.wo(c);a=z.Ye(a+" ");var c=a.firstChild,d=z.KB(this.G);if(z.fv(d))d.fj(a),z.C?window.document.selection&&(b=window.document.selection.createRange(),b.move("character",-1),b.select()):(z.Xu(c),b.eb().focus()),z.LB(this.G),this.G.Cf();else return null;this.U.removeAll()};z.e.Dz=function(){this.U.removeAll()};z.nB=!0;(function(a){z.hB.prototype.execCommand=function(b){var c=this.G;return z.Kn(US,b)&&!c.Rf?(c.wg(),!1):a.apply(this,arguments)}})(z.hB.prototype.execCommand);(function(a,b){z.RF.prototype.execCommand=function(c){var d=this.G;return!z.rb(b,c)||d.Rf||(d.wg(),d.Rf)?a.apply(this,arguments):!1}})(z.RF.prototype.execCommand,["+equation"]);PS="video";TS=z.Uc?"⌘":"ctrl";z.$H[PS]={Ba:PS,na:"插入视频",Wa:"tr-icon tr-video",factory:z.vF};
z.$H["+equation"]={Ba:"+equation",na:{}.H_,Wa:"tr-icon tr-equation",factory:z.vF};z.$H["+bold"].na="粗体 ("+TS+"+b)";z.$H["+italic"].na="斜体 ("+TS+"+i)";z.$H["+underline"].na="下划线 ("+TS+"+u)";z.$H["+superscript"].na="引用内容";z.$H["+insertOrderedList"].na="有序列表";z.$H["+insertUnorderedList"].na="无序列表";z.$H["+removeFormat"].na="清除格式";z.$H.image.na="插入图片";z.$H[PS].na="插入视频";z.$H["+equation"].na="插入公式";z.ka(QS);
QS.prototype.zf=function(a,b){this.config=b;var c,d,f;d=z.L("zm-editable-toolbar-container",a);c=z.L("zm-editable-editor-outer",a);f=z.L("zm-editable-editor-field-element",a);var g=new z.SB(f.id);g.lP=89;var h=RS(d,b);new VR(g,h);z.Ac(g,h);$P(g,new yQ);$P(g,new KR);if(b.loremIpsum_&&($P(g,new MR(b.loremIpsum_)),z.B))g.on("load",function(){z.ld(g.m(),"focus",function(){g.execCommand("clearlorem",!0)})});$P(g,new ZQ);$P(g,new KS);$P(g,new QR);d=new nS;$P(g,d);$P(g,new z.WF);$P(g,new OS);$P(g,new YR);
$P(g,new IR);$P(g,new pR);$P(g,new cS);b.enableFullScreen&&(c=new z.FF({title:"写作模式",jl:c}),$P(g,c));g.on("load",function(){b.useScraper_&&SS(g,h)},!1,this);return[g,h]};z.x("ZH.createRichTextEditor",function(a,b){return QS.ba().zf(a,b)});z.lg("richtexteditor");}).call(this, __z_z__);
//# sourceURL=/static/revved/-/js/closure/richtexteditor.42ea4ea9.js